// watch-after-sales/frontend/src/app/(dashboard)/repairs/new/page.tsx
"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft } from "lucide-react";
import { apiFetch, AppError } from "@/lib/api";
import ErrorAlert from "@/components/ErrorAlert";

export default function NewRepairPage() {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<AppError | null>(null);
  const [form, setForm] = useState({
    customer_name: "",
    customer_phone: "",
    watch_brand: "",
    watch_model: "",
    serial_number: "",
    issue_description: "",
    estimated_price: "",
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    try {
      const body: Record<string, string | number> = {
        customer_name: form.customer_name,
        customer_phone: form.customer_phone,
        watch_brand: form.watch_brand,
        watch_model: form.watch_model,
        serial_number: form.serial_number,
        issue_description: form.issue_description,
      };
      if (form.estimated_price) {
        body.estimated_price = parseFloat(form.estimated_price);
      }
      const res = await apiFetch<{ id: number }>("/repairs", {
        method: "POST",
        body: JSON.stringify(body),
      });
      router.push(`/repairs/${res.id}`);
    } catch (err) {
      setError(err as AppError);
    } finally {
      setLoading(false);
    }
  };

  const updateField = (key: string, value: string) => {
    setForm((prev) => ({ ...prev, [key]: value }));
  };

  return (
    <div className="max-w-2xl mx-auto space-y-4">
      <div className="flex items-center gap-3">
        <button onClick={() => router.back()} className="p-2 hover:bg-gray-100 rounded">
          <ArrowLeft className="w-5 h-5" />
        </button>
        <h2 className="text-xl font-bold">新建寄修工单</h2>
      </div>

      <ErrorAlert error={error} onClose={() => setError(null)} />

      <form onSubmit={handleSubmit} className="bg-white rounded-lg shadow p-6 space-y-4">
        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">客户姓名 *</label>
            <input
              type="text"
              required
              value={form.customer_name}
              onChange={(e) => updateField("customer_name", e.target.value)}
              className="w-full border rounded px-3 py-2 text-sm"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">联系电话 *</label>
            <input
              type="text"
              required
              value={form.customer_phone}
              onChange={(e) => updateField("customer_phone", e.target.value)}
              className="w-full border rounded px-3 py-2 text-sm"
            />
          </div>
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">品牌 *</label>
            <input
              type="text"
              required
              value={form.watch_brand}
              onChange={(e) => updateField("watch_brand", e.target.value)}
              className="w-full border rounded px-3 py-2 text-sm"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">型号 *</label>
            <input
              type="text"
              required
              value={form.watch_model}
              onChange={(e) => updateField("watch_model", e.target.value)}
              className="w-full border rounded px-3 py-2 text-sm"
            />
          </div>
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">序列号</label>
            <input
              type="text"
              value={form.serial_number}
              onChange={(e) => updateField("serial_number", e.target.value)}
              className="w-full border rounded px-3 py-2 text-sm"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">预估价格</label>
            <input
              type="number"
              step="0.01"
              value={form.estimated_price}
              onChange={(e) => updateField("estimated_price", e.target.value)}
              className="w-full border rounded px-3 py-2 text-sm"
            />
          </div>
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">问题描述 *</label>
          <textarea
            required
            rows={4}
            value={form.issue_description}
            onChange={(e) => updateField("issue_description", e.target.value)}
            className="w-full border rounded px-3 py-2 text-sm"
          />
        </div>
        <div className="flex justify-end gap-3">
          <button
            type="button"
            onClick={() => router.back()}
            className="px-4 py-2 border rounded text-sm hover:bg-gray-50"
          >
            取消
          </button>
          <button
            type="submit"
            disabled={loading}
            className="px-4 py-2 bg-blue-600 text-white rounded text-sm hover:bg-blue-700 disabled:opacity-50"
          >
            {loading ? "提交中..." : "提交"}
          </button>
        </div>
      </form>
    </div>
  );
}

// runner-platform/frontend/src/routes/appeals/new/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { page } from '$app/stores';
	import { api, appealTypeMap } from '$lib/api';
	import { user } from '$lib/stores/auth';
	import { onMount } from 'svelte';

	let orderId = $page.url.searchParams.get('order_id') || '';
	let appeal = {
		order_id: 0,
		runner_id: 0,
		type: 'timeout',
		reason: '',
		evidence_url: ''
	};

	let orders: any[] = [];
	let loading = false;
	let error = '';

	async function loadOrders() {
		orders = await api.getOrders();
		if (orderId) {
			appeal.order_id = parseInt(orderId);
		}
	}

	async function handleSubmit() {
		if (!appeal.order_id || !appeal.reason) {
			error = '请填写完整信息';
			return;
		}

		appeal.runner_id = $user?.id || 4;
		loading = true;
		error = '';

		try {
			await api.createAppeal(appeal);
			goto('/appeals');
		} catch (e: any) {
			error = e.message;
		} finally {
			loading = false;
		}
	}

	onMount(() => {
		loadOrders();
	});
</script>

<div class="p-8 max-w-2xl mx-auto">
	<div class="bg-white rounded-xl shadow-sm p-6">
		<h2 class="text-xl font-bold mb-6">提交申诉</h2>

		<form on:submit|preventDefault={handleSubmit} class="space-y-6">
			<div>
				<label class="block text-sm font-medium text-gray-700 mb-2">关联订单</label>
				<select
					bind:value={appeal.order_id}
					class="w-full px-4 py-3 border border-gray-300 rounded-lg"
					required
				>
					<option value={0}>选择订单</option>
					{#each orders as order}
						<option value={order.id}>{order.order_no} - {order.merchant_name}</option>
					{/each}
				</select>
			</div>

			<div>
				<label class="block text-sm font-medium text-gray-700 mb-2">申诉类型</label>
				<select
					bind:value={appeal.type}
					class="w-full px-4 py-3 border border-gray-300 rounded-lg"
				>
					{#each Object.entries(appealTypeMap) as [key, val]}
						<option value={key}>{val}</option>
					{/each}
				</select>
			</div>

			<div>
				<label class="block text-sm font-medium text-gray-700 mb-2">申诉原因</label>
				<textarea
					bind:value={appeal.reason}
					class="w-full px-4 py-3 border border-gray-300 rounded-lg"
					rows="4"
					placeholder="请详细描述申诉原因..."
					required
				/>
			</div>

			<div>
				<label class="block text-sm font-medium text-gray-700 mb-2">证据链接（可选）</label>
				<input
					type="url"
					bind:value={appeal.evidence_url}
					class="w-full px-4 py-3 border border-gray-300 rounded-lg"
					placeholder="https://..."
				/>
			</div>

			{#if error}
				<div class="p-3 bg-red-50 border border-red-200 rounded-lg text-red-600 text-sm">
					{error}
				</div>
			{/if}

			<div class="flex space-x-4">
				<button
					type="button"
					on:click={() => goto('/appeals')}
					class="flex-1 py-3 border border-gray-300 rounded-lg hover:bg-gray-50"
				>
					取消
				</button>
				<button
					type="submit"
					disabled={loading}
					class="flex-1 py-3 bg-purple-600 text-white rounded-lg hover:bg-purple-700 disabled:opacity-50"
				>
					{loading ? '提交中...' : '提交申诉'}
				</button>
			</div>
		</form>
	</div>
</div>
