// watch-service-system/components/common/LoadingState.vue
<template>
  <div class="flex items-center justify-center py-16">
    <div class="flex flex-col items-center">
      <div class="w-10 h-10 border-4 border-primary-200 border-t-primary-700 rounded-full animate-spin mb-4"></div>
      <p class="text-gray-500 text-sm">{{ text }}</p>
    </div>
  </div>
</template>

<script setup lang="ts">
interface Props {
  text?: string;
}

withDefaults(defineProps<Props>(), {
  text: '加载中...',
});
</script>

// golf-equipment-tracker/src/components/ui/LoadingState.tsx
import React from "react";
import { Loader2 } from "lucide-react";

interface LoadingStateProps {
  message?: string;
  size?: "sm" | "md" | "lg";
}

export const LoadingState: React.FC<LoadingStateProps> = ({
  message = "加载中...",
  size = "md",
}) => {
  const sizeClasses = {
    sm: "w-4 h-4",
    md: "w-8 h-8",
    lg: "w-12 h-12",
  };

  return (
    <div className="flex flex-col items-center justify-center py-12 px-4">
      <Loader2 className={`${sizeClasses[size]} text-blue-500 animate-spin mb-4`} />
      <p className="text-sm text-gray-500">{message}</p>
    </div>
  );
};
