// frontend/src/components/Layout.vue
<template>
  <div class="flex h-screen bg-gray-50">
    <aside class="w-64 bg-white shadow-lg">
      <div class="p-6 border-b">
        <h1 class="text-xl font-bold text-blue-600 flex items-center gap-2">
          <component :is="icons.Home" class="w-6 h-6" />
          游学营地管理
        </h1>
      </div>
      <nav class="p-4">
        <ul class="space-y-2">
          <li v-for="item in menuItems" :key="item.path">
            <router-link
              :to="item.path"
              class="flex items-center gap-3 px-4 py-3 rounded-lg transition-colors"
              :class="{
                'bg-blue-50 text-blue-600': isActive(item.path),
                'text-gray-600 hover:bg-gray-50': !isActive(item.path),
              }"
            >
              <component :is="item.icon" class="w-5 h-5" />
              <span>{{ item.name }}</span>
              <span
                v-if="item.badge"
                class="ml-auto bg-red-500 text-white text-xs px-2 py-0.5 rounded-full"
              >
                {{ item.badge }}
              </span>
            </router-link>
          </li>
        </ul>
      </nav>
      <div class="absolute bottom-0 left-0 right-0 p-4 border-t">
        <div class="flex items-center gap-3 mb-4">
          <div class="w-10 h-10 bg-blue-100 rounded-full flex items-center justify-center">
            <component :is="icons.User" class="w-5 h-5 text-blue-600" />
          </div>
          <div>
            <div class="font-medium text-gray-800">{{ user?.name || '用户' }}</div>
            <div class="text-sm text-gray-500">{{ roleName }}</div>
          </div>
        </div>
        <button
          @click="handleLogout"
          class="w-full flex items-center gap-2 px-4 py-2 text-gray-600 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors"
        >
          <component :is="icons.LogOut" class="w-4 h-4" />
          退出登录
        </button>
      </div>
    </aside>

    <main class="flex-1 overflow-auto">
      <header class="bg-white shadow-sm px-8 py-4 flex items-center justify-between">
        <h2 class="text-lg font-semibold text-gray-800">{{ pageTitle }}</h2>
        <div class="flex items-center gap-4">
          <el-tag :type="roleTagType" size="large">
            当前角色: {{ roleName }}
          </el-tag>
        </div>
      </header>
      <div class="p-8">
        <router-view />
      </div>
    </main>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useUserStore } from '@/stores/user'
import * as icons from 'lucide-vue-next'

const route = useRoute()
const router = useRouter()
const userStore = useUserStore()

const user = computed(() => userStore.user)

const roleName = computed(() => {
  const roles: Record<string, string> = {
    director: '营地主任',
    teacher: '班务老师',
    logistics: '后勤协调',
  }
  return roles[user.value?.role] || '未知'
})

const roleTagType = computed(() => {
  const types: Record<string, string> = {
    director: 'danger',
    teacher: 'primary',
    logistics: 'success',
  }
  return types[user.value?.role] || 'info'
})

const menuItems = computed(() => {
  const baseMenu = [
    { path: '/dashboard', name: '仪表盘', icon: icons.LayoutDashboard },
    { path: '/campers', name: '营员管理', icon: icons.Users },
    { path: '/rooms', name: '分房管理', icon: icons.BedDouble },
    { path: '/materials', name: '物资管理', icon: icons.Package },
    { path: '/resupply', name: '补领申请', icon: icons.RefreshCw },
    { path: '/check-in', name: '活动签到', icon: icons.CalendarCheck },
    { path: '/medical', name: '医疗上报', icon: icons.Heart },
  ]
  return baseMenu
})

const pageTitle = computed(() => {
  return route.meta?.title as string || '仪表盘'
})

const isActive = (path: string) => {
  return route.path.startsWith(path)
}

const handleLogout = () => {
  userStore.logout()
  router.push('/login')
}

onMounted(() => {
  userStore.loadUser()
})
</script>

// frontend/src/components/Layout.jsx
import { useState } from 'react'
import { Link, useLocation } from 'react-router-dom'
import { 
  Home, ClipboardCheck, Wrench, Users, Menu, X, 
  User, ChevronDown 
} from 'lucide-react'

const menuItems = [
  { path: '/', name: '工作台', icon: Home },
  { path: '/inspections', name: '巡检管理', icon: ClipboardCheck },
  { path: '/rectifications', name: '整改管理', icon: Wrench },
]

const currentUser = {
  id: 1,
  name: '张监理',
  role: 'supervisor'
}

export default function Layout({ children }) {
  const [sidebarOpen, setSidebarOpen] = useState(true)
  const [userMenuOpen, setUserMenuOpen] = useState(false)
  const location = useLocation()

  return (
    <div className="min-h-screen bg-gray-50">
      <aside className={`fixed left-0 top-0 z-40 h-screen bg-white shadow-lg transition-all duration-300 ${sidebarOpen ? 'w-64' : 'w-20'}`}>
        <div className="flex h-16 items-center justify-between border-b px-4">
          {sidebarOpen && (
            <span className="text-lg font-bold text-blue-600">家装监理系统</span>
          )}
          <button
            onClick={() => setSidebarOpen(!sidebarOpen)}
            className="rounded-lg p-2 hover:bg-gray-100"
          >
            {sidebarOpen ? <X size={20} /> : <Menu size={20} />}
          </button>
        </div>
        <nav className="mt-6 px-3">
          {menuItems.map((item) => {
            const Icon = item.icon
            const isActive = location.pathname === item.path || 
              (item.path !== '/' && location.pathname.startsWith(item.path))
            return (
              <Link
                key={item.path}
                to={item.path}
                className={`mb-2 flex items-center rounded-lg px-4 py-3 transition-colors ${
                  isActive 
                    ? 'bg-blue-50 text-blue-600' 
                    : 'text-gray-700 hover:bg-gray-100'
                }`}
              >
                <Icon size={20} />
                {sidebarOpen && <span className="ml-3">{item.name}</span>}
              </Link>
            )
          })}
        </nav>
      </aside>

      <div className={`${sidebarOpen ? 'ml-64' : 'ml-20'} transition-all duration-300`}>
        <header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b bg-white px-6 shadow-sm">
          <div className="text-lg font-semibold text-gray-800">
            {menuItems.find(item => location.pathname === item.path || 
              (item.path !== '/' && location.pathname.startsWith(item.path)))?.name || '工作台'}
          </div>
          <div className="relative">
            <button
              onClick={() => setUserMenuOpen(!userMenuOpen)}
              className="flex items-center gap-2 rounded-lg px-3 py-2 hover:bg-gray-100"
            >
              <div className="flex h-8 w-8 items-center justify-center rounded-full bg-blue-100">
                <User size={18} className="text-blue-600" />
              </div>
              <span className="text-sm font-medium text-gray-700">{currentUser.name}</span>
              <ChevronDown size={16} className="text-gray-500" />
            </button>
            {userMenuOpen && (
              <div className="absolute right-0 mt-2 w-48 rounded-lg border bg-white py-2 shadow-lg">
                <div className="px-4 py-2">
                  <p className="text-sm font-medium text-gray-900">{currentUser.name}</p>
                  <p className="text-xs text-gray-500">
                    {currentUser.role === 'supervisor' ? '监理负责人' : 
                     currentUser.role === 'manager' ? '项目管家' : '业主客服'}
                  </p>
                </div>
              </div>
            )}
          </div>
        </header>

        <main className="p-6">
          {children}
        </main>
      </div>
    </div>
  )
}

export { currentUser }
