// watch-after-sales/frontend/src/app/login/page.tsx
"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Watch, LogIn } from "lucide-react";
import { apiFetch, AppError } from "@/lib/api";
import { useAuthStore } from "@/store/authStore";
import ErrorAlert from "@/components/ErrorAlert";

export default function LoginPage() {
  const router = useRouter();
  const { login } = useAuthStore();
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<AppError | null>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    try {
      const res = await apiFetch<{ token: string; user: { id: number; username: string; role: string; display_name: string } }>("/auth/login", {
        method: "POST",
        body: JSON.stringify({ username, password }),
      });
      login(res.token, res.user);
      router.replace("/");
    } catch (err) {
      setError(err as AppError);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50">
      <div className="w-full max-w-md">
        <div className="text-center mb-8">
          <Watch className="w-12 h-12 text-blue-600 mx-auto mb-3" />
          <h1 className="text-2xl font-bold">钟表售后寄修系统</h1>
          <p className="text-gray-500 mt-1">请登录以继续</p>
        </div>
        <form onSubmit={handleSubmit} className="bg-white rounded-lg shadow p-8 space-y-5">
          <ErrorAlert error={error} onClose={() => setError(null)} />
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">用户名</label>
            <input
              type="text"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              required
              className="w-full border rounded px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholder="请输入用户名"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">密码</label>
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
              className="w-full border rounded px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholder="请输入密码"
            />
          </div>
          <button
            type="submit"
            disabled={loading}
            className="w-full bg-blue-600 text-white py-2.5 rounded text-sm font-medium hover:bg-blue-700 disabled:opacity-50 flex items-center justify-center gap-2"
          >
            <LogIn className="w-4 h-4" />
            {loading ? "登录中..." : "登录"}
          </button>
        </form>
      </div>
    </div>
  );
}

// runner-platform/frontend/src/routes/login/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { api } from '$lib/api';
	import { setAuth } from '$lib/stores/auth';

	let username = '';
	let password = '';
	let error = '';
	let loading = false;

	async function handleLogin() {
		error = '';
		loading = true;
		try {
			const result = await api.login(username, password);
			setAuth(result.token, result.user);
			goto('/orders');
		} catch (e: any) {
			error = e.message;
		} finally {
			loading = false;
		}
	}
</script>

<div class="min-h-screen flex items-center justify-center bg-gradient-to-br from-blue-600 to-purple-700">
	<div class="bg-white rounded-xl shadow-2xl p-8 w-full max-w-md">
		<div class="text-center mb-8">
			<h1 class="text-3xl font-bold text-gray-900 mb-2">🚴 跑腿平台</h1>
			<p class="text-gray-500">订单派发与超时申诉系统</p>
		</div>

		<form on:submit|preventDefault={handleLogin} class="space-y-6">
			<div>
				<label class="block text-sm font-medium text-gray-700 mb-2">用户名</label>
				<input
					type="text"
					bind:value={username}
					class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
					placeholder="请输入用户名"
					required
				/>
			</div>

			<div>
				<label class="block text-sm font-medium text-gray-700 mb-2">密码</label>
				<input
					type="password"
					bind:value={password}
					class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
					placeholder="请输入密码"
					required
				/>
			</div>

			{#if error}
				<div class="p-3 bg-red-50 border border-red-200 rounded-lg text-red-600 text-sm">
					{error}
				</div>
			{/if}

			<button
				type="submit"
				disabled={loading}
				class="w-full py-3 bg-blue-600 text-white font-medium rounded-lg hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
			>
				{loading ? '登录中...' : '登 录'}
			</button>
		</form>

		<div class="mt-6 pt-6 border-t border-gray-100">
			<p class="text-xs text-gray-500 mb-3">测试账号（密码均为 123456）：</p>
			<div class="grid grid-cols-2 gap-2 text-xs">
				<div class="p-2 bg-gray-50 rounded"><span class="font-medium">admin</span> - 运营经理</div>
				<div class="p-2 bg-gray-50 rounded"><span class="font-medium">dispatch_zhang</span> - 调度</div>
				<div class="p-2 bg-gray-50 rounded"><span class="font-medium">cs_li</span> - 客服</div>
				<div class="p-2 bg-gray-50 rounded"><span class="font-medium">runner_wang</span> - 骑手</div>
			</div>
		</div>
	</div>
</div>
