// web/src/lib/components/Header.svelte
<script>
  import { page } from '$app/stores';
  import { Bell, Search } from 'lucide-svelte';
  import { user } from '../../stores/user';

  let currentUser = null;
  user.subscribe((v) => (currentUser = v));

  const pageTitles = {
    '/': '首页看板',
    '/members': '会员管理',
    '/memberships': '套餐管理',
    '/orders': '续费订单',
    '/repairs': '设备报修',
    '/refunds': '退款申诉',
    '/activities': '活动推送',
    '/sites': '站点设备',
  };

  $: title = pageTitles[$page.url.pathname] || '首页';
</script>

<header class="bg-white border-b border-gray-200 px-6 py-4">
  <div class="flex items-center justify-between">
    <div>
      <h1 class="text-xl font-bold text-gray-900">{title}</h1>
      <p class="text-sm text-gray-500">
        {new Date().toLocaleDateString('zh-CN', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
      </p>
    </div>

    <div class="flex items-center gap-4">
      <div class="relative">
        <Search class="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
        <input type="text" placeholder="搜索..." class="input pl-9 py-2 w-64 text-sm" />
      </div>

      <button class="relative p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-lg">
        <Bell class="w-5 h-5" />
        <span class="absolute top-1 right-1 w-2 h-2 bg-red-500 rounded-full"></span>
      </button>

      <div class="flex items-center gap-2 pl-4 border-l border-gray-200">
        <div class="w-8 h-8 bg-primary-200 rounded-full flex items-center justify-center">
          <span class="text-primary-700 font-medium text-sm">{currentUser?.name?.charAt(0) || 'U'}</span>
        </div>
      </div>
    </div>
  </div>
</header>

// frontend/src/components/layout/Header.tsx
import React, { useState } from 'react';
import { Bell, User, ChevronDown } from 'lucide-react';
import { RoleSwitcher } from '@/components/shared/RoleSwitcher';
import { useRole } from '@/hooks/useRole';
import { useAlert } from '@/hooks/useAlert';
import { AlertTypeLabels } from '@/types';
import { useNavigate } from 'react-router-dom';

export function Header() {
  const { currentUser } = useRole();
  const { alerts, unreadCount, markAsRead } = useAlert();
  const [showNotifications, setShowNotifications] = useState(false);
  const navigate = useNavigate();

  const recentAlerts = alerts.slice(0, 5);

  const handleAlertClick = (alert: any) => {
    markAsRead(alert.id);
    setShowNotifications(false);
    navigate(`/${alert.targetType}`);
  };

  return (
    <header className="h-16 bg-white border-b border-gray-200 flex items-center justify-between px-6">
      <div className="flex items-center gap-4">
        <h2 className="text-lg font-medium text-gray-800">
          地坪施工-材料管理系统
        </h2>
      </div>

      <div className="flex items-center gap-4">
        <RoleSwitcher />

        <div className="relative">
          <button
            onClick={() => setShowNotifications(!showNotifications)}
            className="relative p-2 text-gray-500 hover:text-gray-700 hover:bg-gray-100 rounded-lg transition-colors"
          >
            <Bell className="w-5 h-5" />
            {unreadCount > 0 && (
              <span className="absolute -top-1 -right-1 w-5 h-5 bg-danger-500 text-white text-xs rounded-full flex items-center justify-center">
                {unreadCount > 9 ? '9+' : unreadCount}
              </span>
            )}
          </button>

          {showNotifications && (
            <div className="absolute right-0 mt-2 w-80 bg-white border border-gray-200 rounded-lg shadow-lg z-50">
              <div className="px-4 py-3 border-b border-gray-200">
                <h3 className="font-medium text-gray-800">通知中心</h3>
              </div>
              <div className="max-h-80 overflow-y-auto">
                {recentAlerts.length === 0 ? (
                  <div className="px-4 py-8 text-center text-gray-500 text-sm">
                    暂无通知
                  </div>
                ) : (
                  recentAlerts.map((alert) => (
                    <button
                      key={alert.id}
                      onClick={() => handleAlertClick(alert)}
                      className={`w-full px-4 py-3 text-left hover:bg-gray-50 border-b border-gray-100 last:border-0 ${
                        !alert.read ? 'bg-blue-50' : ''
                      }`}
                    >
                      <div className="flex items-start justify-between">
                        <div className="flex-1">
                          <div className="flex items-center gap-2">
                            <span className="text-sm font-medium text-gray-800">
                              {alert.title}
                            </span>
                            {!alert.read && (
                              <span className="w-2 h-2 bg-primary-500 rounded-full"></span>
                            )}
                          </div>
                          <p className="text-xs text-gray-500 mt-1 line-clamp-2">
                            {alert.description}
                          </p>
                        </div>
                      </div>
                      <div className="text-xs text-gray-400 mt-2">
                        {AlertTypeLabels[alert.type]} · {new Date(alert.createdAt).toLocaleDateString()}
                      </div>
                    </button>
                  ))
                )}
              </div>
            </div>
          )}
        </div>

        <div className="flex items-center gap-3 pl-4 border-l border-gray-200">
          <div className="w-8 h-8 rounded-full bg-gray-200 flex items-center justify-center overflow-hidden">
            {currentUser?.avatar ? (
              <img src={currentUser.avatar} alt={currentUser.name} className="w-full h-full object-cover" />
            ) : (
              <User className="w-4 h-4 text-gray-500" />
            )}
          </div>
          <div className="hidden md:block">
            <div className="text-sm font-medium text-gray-800">
              {currentUser?.name || '未登录'}
            </div>
          </div>
        </div>
      </div>
    </header>
  );
}
