// src/views/Login.vue
<template>
  <div class="login-page">
    <div class="login-card">
      <div class="login-header">
        <span class="logo-icon">🌾</span>
        <h1 class="login-title">农机合作社管理系统</h1>
        <p class="login-subtitle">地块进度与回访评价</p>
      </div>
      
      <form class="login-form" @submit.prevent="handleLogin">
        <div class="form-item">
          <label class="form-label">用户名</label>
          <input 
            type="text" 
            v-model="username" 
            class="form-input" 
            placeholder="请输入用户名"
            required
          />
        </div>
        
        <div class="form-item">
          <label class="form-label">密码</label>
          <input 
            type="password" 
            v-model="password" 
            class="form-input" 
            placeholder="请输入密码"
            required
          />
        </div>
        
        <button type="submit" class="btn btn-primary login-btn" :disabled="loading">
          {{ loading ? '登录中...' : '登录' }}
        </button>
      </form>
      
      <div class="login-tips">
        <p class="tips-title">演示账号：</p>
        <div class="tips-list">
          <div class="tip-item">
            <span class="tip-role">理事：</span>
            <span class="tip-account">director / 123456</span>
          </div>
          <div class="tip-item">
            <span class="tip-role">调度：</span>
            <span class="tip-account">dispatcher / 123456</span>
          </div>
          <div class="tip-item">
            <span class="tip-role">机手：</span>
            <span class="tip-account">operator / 123456</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useUserStore } from '../stores/user'
import { useToastStore } from '../stores/toast'

const router = useRouter()
const userStore = useUserStore()
const toastStore = useToastStore()

const username = ref('')
const password = ref('')
const loading = ref(false)

async function handleLogin() {
  loading.value = true
  try {
    const success = await userStore.login(username.value, password.value)
    if (success) {
      toastStore.success('登录成功')
      router.push('/')
    } else {
      toastStore.error('用户名或密码错误')
    }
  } catch (e) {
    toastStore.error('登录失败，请重试')
  } finally {
    loading.value = false
  }
}

onMounted(async () => {
  const hasSession = await userStore.restoreSession()
  if (hasSession) {
    router.push('/')
  }
})
</script>

<style scoped>
.login-page {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  padding: 20px;
}

.login-card {
  width: 100%;
  max-width: 400px;
  background: #fff;
  border-radius: 12px;
  padding: 40px 32px;
  box-shadow: 0 10px 40px rgba(0, 0, 0, 0.2);
}

.login-header {
  text-align: center;
  margin-bottom: 32px;
}

.logo-icon {
  font-size: 48px;
  display: block;
  margin-bottom: 12px;
}

.login-title {
  font-size: 24px;
  font-weight: 600;
  color: #333;
  margin-bottom: 8px;
}

.login-subtitle {
  font-size: 14px;
  color: #999;
}

.login-form {
  margin-bottom: 24px;
}

.login-btn {
  width: 100%;
  padding: 12px;
  font-size: 16px;
  margin-top: 8px;
}

.login-btn:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.login-tips {
  padding: 16px;
  background: #f5f7fa;
  border-radius: 8px;
}

.tips-title {
  font-size: 13px;
  color: #666;
  margin-bottom: 12px;
  font-weight: 500;
}

.tips-list {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.tip-item {
  font-size: 12px;
  color: #666;
  display: flex;
  align-items: center;
}

.tip-role {
  width: 48px;
  font-weight: 500;
  color: #333;
}

.tip-account {
  font-family: monospace;
  background: #e8e8e8;
  padding: 2px 8px;
  border-radius: 4px;
}
</style>

// client/src/routes/login/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { login } from '../lib/api';

  let username = 'manager';
  let password = '123456';
  let loading = false;
  let error = '';

  const accounts = [
    { u: 'manager', n: '林店长', r: '门店店长', hint: '全局 · 团队 · 异常统筹' },
    { u: 'editor', n: '陈选片', r: '选片师', hint: '上传版本 · 确认选片' },
    { u: 'service', n: '王管家', r: '客服管家', hint: '档期改期 · 尾款催收 · 客诉' }
  ];

  async function submit() {
    loading = true; error = '';
    try {
      const r = await login(username, password);
      localStorage.setItem('token', r.token);
      localStorage.setItem('user', JSON.stringify(r.user));
      await goto('/orders');
    } catch (e: any) {
      error = e.message || '登录失败';
    } finally {
      loading = false;
    }
  }

  function pick(u: string) {
    username = u; password = '123456';
  }
</script>

<div class="wrap">
  <div class="left">
    <div class="mark serif">缦纱集</div>
    <h1 class="serif">档期 · 选片 · 尾款<br/>一条可追溯的链</h1>
    <p class="desc">
      把散在档期表、修片群和客户聊天里的信息收拢，让改期、版本、催收都带上时间戳。
      客诉一来，不用再翻聊天记录找证据。
    </p>
    <div class="feat">
      <div><span>01</span>拍摄档期与改期留痕</div>
      <div><span>02</span>选片版本按追加管理</div>
      <div><span>03</span>尾款与异常同一时间线</div>
    </div>
  </div>

  <div class="right">
    <div class="card">
      <h2 class="serif">登录协同台</h2>
      <form on:submit|preventDefault={submit}>
        <label>账号
          <input bind:value={username} placeholder="manager / editor / service" />
        </label>
        <label>密码
          <input bind:value={password} type="password" placeholder="默认 123456" />
        </label>
        {#if error}<div class="error">{error}</div>{/if}
        <button class="primary" type="submit" disabled={loading}>
          {loading ? '登录中…' : '进入协同台'}
        </button>
      </form>

      <div class="quick">
        <div class="quick-title">测试账号 · 点一下切换</div>
        <div class="quick-list">
          {#each accounts as a}
            <button class="acct" class:on={username === a.u} on:click={() => pick(a.u)}>
              <div class="acct-u">{a.u}</div>
              <div class="acct-n">{a.n} · {a.r}</div>
              <div class="acct-h">{a.hint}</div>
            </button>
          {/each}
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  .wrap {
    min-height: 100vh;
    display: grid;
    grid-template-columns: 1.1fr 1fr;
    gap: 40px;
    padding: 64px 80px;
    align-items: center;
  }
  .left { max-width: 520px; }
  .mark {
    display: inline-block;
    padding: 6px 14px; border-radius: 999px;
    background: linear-gradient(135deg, var(--accent), #5a2626);
    color: #fff; letter-spacing: 4px; font-weight: 900;
    font-size: 14px;
  }
  h1 { font-size: 44px; line-height: 1.2; margin: 22px 0 18px; letter-spacing: 2px; }
  .desc { color: var(--ink-2); line-height: 1.9; font-size: 15px; }
  .feat { margin-top: 32px; display: grid; gap: 10px; }
  .feat div {
    display: flex; align-items: center; gap: 16px;
    padding: 14px 18px; border-radius: 12px;
    background: rgba(255, 250, 241, 0.7);
    border: 1px solid var(--line);
  }
  .feat span {
    font-family: 'Noto Serif SC', serif; font-weight: 900;
    color: var(--accent); font-size: 18px;
  }

  .right { display: flex; justify-content: center; }
  .card {
    width: 100%; max-width: 420px;
    padding: 36px; border-radius: 20px;
    background: var(--soft);
    border: 1px solid var(--line);
    box-shadow: var(--shadow);
  }
  .card h2 { margin: 0 0 22px; font-size: 24px; letter-spacing: 2px; }
  form { display: grid; gap: 14px; }
  label { font-size: 13px; color: var(--ink-2); display: grid; gap: 6px; }
  input {
    padding: 12px 14px; border-radius: 10px;
    border: 1px solid var(--line); background: #fff;
    font-size: 14px; color: var(--ink);
    transition: border-color 0.15s;
  }
  input:focus { outline: none; border-color: var(--accent-2); }
  .primary {
    margin-top: 6px;
    padding: 12px; border-radius: 10px; border: 0;
    background: linear-gradient(135deg, var(--accent), #6a2929);
    color: #fff; font-weight: 600; font-size: 15px;
    box-shadow: 0 6px 20px rgba(139, 58, 58, 0.3);
  }
  .primary:disabled { opacity: 0.6; }
  .error { padding: 10px 12px; border-radius: 10px; background: #fbe7e5; color: var(--bad); font-size: 13px; }

  .quick { margin-top: 28px; padding-top: 22px; border-top: 1px dashed var(--line); }
  .quick-title { font-size: 12px; color: var(--ink-2); margin-bottom: 10px; letter-spacing: 0.5px; }
  .quick-list { display: grid; gap: 10px; }
  .acct {
    text-align: left; padding: 12px 14px; border-radius: 12px;
    background: #fff; border: 1px solid var(--line); color: var(--ink);
    transition: all 0.15s;
  }
  .acct:hover { border-color: var(--accent-2); }
  .acct.on { background: linear-gradient(135deg, #f6e1c2, #f0cf9d); border-color: #c49a6c; }
  .acct-u { font-size: 12px; color: var(--accent); font-weight: 700; letter-spacing: 1px; }
  .acct-n { font-size: 14px; font-weight: 600; margin-top: 2px; }
  .acct-h { font-size: 12px; color: var(--ink-2); margin-top: 2px; }
</style>
