// src/components/common/StatusBadge.tsx
import { cn } from '@/lib/utils';

interface StatusBadgeProps {
  status: string;
  label?: string;
  variant?: 'default' | 'success' | 'warning' | 'danger' | 'info' | 'amber';
  size?: 'sm' | 'md';
  className?: string;
}

export function StatusBadge({
  status,
  label,
  variant = 'default',
  size = 'sm',
  className,
}: StatusBadgeProps) {
  const variants = {
    default: 'bg-gray-100 text-gray-700',
    success: 'bg-green-100 text-green-700',
    warning: 'bg-amber-100 text-amber-700',
    danger: 'bg-red-100 text-red-700',
    info: 'bg-blue-100 text-blue-700',
    amber: 'bg-amber-100 text-amber-700',
  };

  const sizes = {
    sm: 'px-2 py-0.5 text-xs',
    md: 'px-2.5 py-1 text-sm',
  };

  return (
    <span className={cn(
      'inline-flex items-center font-medium rounded-full',
      variants[variant],
      sizes[size],
      className
    )}>
      {label || status}
    </span>
  );
}

// components/StatusBadge.vue
<template>
  <span :class="[baseClass, customClass]">
    <component v-if="icon" :is="icon" class="w-3 h-3 mr-1" />
    {{ label }}
  </span>
</template>

<script setup lang="ts">
interface Props {
  label: string
  variant?: 'default' | 'success' | 'warning' | 'danger' | 'info' | 'gold'
  customClass?: string
  icon?: any
}

withDefaults(defineProps<Props>(), {
  variant: 'default',
  customClass: '',
})

const variantClasses: Record<string, string> = {
  default: 'bg-gray-100 text-gray-700',
  success: 'bg-forest-100 text-forest-700',
  warning: 'bg-yellow-100 text-yellow-700',
  danger: 'bg-coral-100 text-coral-700',
  info: 'bg-blue-100 text-blue-700',
  gold: 'bg-gold-100 text-gold-700',
}

const baseClass = computed(() => 
  `inline-flex items-center px-2.5 py-1 rounded-full text-xs font-medium ${variantClasses[props.variant || 'default']}`
)
</script>
