// commercial-cleaning-tracker/frontend/src/lib/components/Layout.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { currentUser, logout } from '$lib/stores';

	export let title: string;
	export let activeMenu: string;

	const roleLabels: Record<string, string> = {
		manager: '项目主管',
		scheduler: '排班专员',
		inspector: '质检员',
		worker: '清洁员'
	};

	function handleLogout() {
		logout();
		goto('/');
	}

	$: menuItems = getMenuItems($currentUser?.Role || '');

	function getMenuItems(role: string) {
		switch (role) {
			case 'manager':
				return [
					{ id: 'dashboard', label: '数据看板', path: '/manager' },
					{ id: 'trace', label: '连续回查', path: '/manager/trace' },
					{ id: 'schedule', label: '排班管理', path: '/manager/schedule' },
					{ id: 'followup', label: '回访跟踪', path: '/manager/followup' },
					{ id: 'projects', label: '项目列表', path: '/manager/projects' }
				];
			case 'scheduler':
				return [
					{ id: 'schedule', label: '排班管理', path: '/scheduler' },
					{ id: 'material', label: '耗材审批', path: '/scheduler/material' },
					{ id: 'projects', label: '项目列表', path: '/scheduler/projects' }
				];
			case 'inspector':
				return [
					{ id: 'inspect', label: '质检录入', path: '/inspector' },
					{ id: 'trace', label: '连续回查', path: '/inspector/trace' },
					{ id: 'rect', label: '整改追踪', path: '/inspector/rect' }
				];
			case 'worker':
				return [
					{ id: 'shifts', label: '我的排班', path: '/worker' },
					{ id: 'checkin', label: '打卡', path: '/worker/checkin' },
					{ id: 'material', label: '耗材申领', path: '/worker/material' },
					{ id: 'rect', label: '整改任务', path: '/worker/rect' }
				];
			default:
				return [];
		}
	}
</script>

<div class="layout">
	<aside class="sidebar">
		<div class="logo">
			<h2>清洁管理系统</h2>
		</div>
		<nav class="menu">
			{#each menuItems as item}
				<button
					class={`menu-item ${activeMenu === item.id ? 'active' : ''}`}
					on:click={() => goto(item.path)}
				>
					{item.label}
				</button>
			{/each}
		</nav>
	</aside>

	<div class="main">
		<header class="header">
			<h1>{title}</h1>
			<div class="user-info">
				<span class="user-name">{$currentUser?.Name}</span>
				<span class="user-role">{roleLabels[$currentUser?.Role || '']}</span>
				<button class="logout-btn" on:click={handleLogout}>退出</button>
			</div>
		</header>

		<div class="content">
			<slot />
		</div>
	</div>
</div>

<style>
	.layout {
		display: flex;
		min-height: 100vh;
	}

	.sidebar {
		width: 240px;
		background: linear-gradient(180deg, #2d3748 0%, #1a202c 100%);
		color: white;
		padding: 20px 0;
		flex-shrink: 0;
	}

	.logo {
		padding: 0 20px 20px;
		border-bottom: 1px solid #4a5568;
		margin-bottom: 16px;
	}

	.logo h2 {
		font-size: 18px;
		font-weight: 600;
	}

	.menu {
		padding: 0 12px;
	}

	.menu-item {
		display: block;
		width: 100%;
		padding: 12px 16px;
		background: transparent;
		border: none;
		color: #a0aec0;
		text-align: left;
		font-size: 14px;
		border-radius: 6px;
		cursor: pointer;
		transition: all 0.2s;
		margin-bottom: 4px;
	}

	.menu-item:hover {
		background: rgba(255, 255, 255, 0.1);
		color: white;
	}

	.menu-item.active {
		background: #667eea;
		color: white;
	}

	.main {
		flex: 1;
		display: flex;
		flex-direction: column;
		min-width: 0;
	}

	.header {
		background: white;
		padding: 20px 32px;
		border-bottom: 1px solid #e2e8f0;
		display: flex;
		align-items: center;
		justify-content: space-between;
	}

	.header h1 {
		font-size: 20px;
		font-weight: 600;
	}

	.user-info {
		display: flex;
		align-items: center;
		gap: 12px;
	}

	.user-name {
		font-weight: 500;
	}

	.user-role {
		padding: 4px 10px;
		background: #edf2f7;
		border-radius: 4px;
		font-size: 12px;
		color: #4a5568;
	}

	.logout-btn {
		padding: 6px 16px;
		background: #fff;
		border: 1px solid #e2e8f0;
		border-radius: 6px;
		cursor: pointer;
		font-size: 13px;
		color: #4a5568;
		transition: all 0.2s;
	}

	.logout-btn:hover {
		background: #f7fafc;
		border-color: #cbd5e0;
	}

	.content {
		flex: 1;
		padding: 24px 32px;
		overflow: auto;
	}
</style>

// src/views/Layout.vue
<template>
  <el-container class="layout-container">
    <el-aside width="220px" class="sidebar">
      <div class="sidebar-header">
        <div class="logo">🏪</div>
        <div class="brand">文创商店</div>
      </div>
      
      <el-menu
        :default-active="activeMenu"
        class="sidebar-menu"
        @select="handleMenuSelect"
      >
        <el-menu-item index="/dashboard">
          <el-icon><DataBoard /></el-icon>
          <span>业务看板</span>
        </el-menu-item>
        
        <template v-if="isManager || isPlanner">
          <el-menu-item index="/members">
            <el-icon><User /></el-icon>
            <span>会员管理</span>
          </el-menu-item>
        </template>
        
        <template v-if="isPlanner || isWarehouse">
          <el-menu-item index="/products">
            <el-icon><Goods /></el-icon>
            <span>商品管理</span>
          </el-menu-item>
        </template>
        
        <el-menu-item index="/orders">
          <el-icon><Document /></el-icon>
          <span>兑换订单</span>
          <el-badge v-if="pendingCount > 0" :value="pendingCount" class="menu-badge" />
        </el-menu-item>
        
        <template v-if="isManager">
          <el-menu-item index="/verify">
            <el-icon><CircleCheck /></el-icon>
            <span>核销管理</span>
          </el-menu-item>
        </template>
        
        <template v-if="isWarehouse">
          <el-menu-item index="/inventory">
            <el-icon><Box /></el-icon>
            <span>库存管理</span>
          </el-menu-item>
        </template>
        
        <el-menu-item index="/inspection">
          <el-icon><Warning /></el-icon>
          <span>巡店问题</span>
          <el-badge v-if="issueCount > 0" :value="issueCount" type="warning" class="menu-badge" />
        </el-menu-item>
        
        <el-menu-item index="/settings">
          <el-icon><Setting /></el-icon>
          <span>系统说明</span>
        </el-menu-item>
      </el-menu>
    </el-aside>

    <el-container>
      <el-header class="header">
        <div class="header-left">
          <el-breadcrumb separator="/">
            <el-breadcrumb-item>{{ pageTitle }}</el-breadcrumb-item>
          </el-breadcrumb>
        </div>
        
        <div class="header-right">
          <div class="current-role">
            <span class="role-tag" :class="currentRoleClass">
              {{ currentRoleLabel }}
            </span>
          </div>
          
          <el-dropdown @command="handleCommand">
            <div class="user-info">
              <span class="avatar">{{ currentUser?.avatar }}</span>
              <span class="username">{{ currentUser?.name }}</span>
              <el-icon class="dropdown-icon"><ArrowDown /></el-icon>
            </div>
            <template #dropdown>
              <el-dropdown-menu>
                <el-dropdown-item command="switch">切换角色</el-dropdown-item>
                <el-dropdown-item command="logout" divided>退出登录</el-dropdown-item>
              </el-dropdown-menu>
            </template>
          </el-dropdown>
        </div>
      </el-header>

      <el-main class="main-content">
        <router-view v-slot="{ Component }">
          <transition name="fade" mode="out-in">
            <component :is="Component" />
          </transition>
        </router-view>
      </el-main>
    </el-container>
  </el-container>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { 
  DataBoard, User, Goods, Document, CircleCheck, 
  Box, Warning, Setting, ArrowDown 
} from '@element-plus/icons-vue'
import { useAuthStore, useOrderStore } from '@/stores'
import { RoleLabels } from '@/types'

const router = useRouter()
const route = useRoute()
const authStore = useAuthStore()
const orderStore = useOrderStore()

const currentUser = computed(() => authStore.currentUser)
const isManager = computed(() => authStore.isManager)
const isPlanner = computed(() => authStore.isPlanner)
const isWarehouse = computed(() => authStore.isWarehouse)

const currentRoleLabel = computed(() => {
  if (!currentUser.value) return ''
  return RoleLabels[currentUser.value.role] || ''
})

const currentRoleClass = computed(() => {
  if (!currentUser.value) return ''
  return `role-${currentUser.value.role.replace('_', '-')}`
})

const activeMenu = computed(() => route.path)

const pageTitle = computed(() => {
  return (route.meta.title as string) || '业务看板'
})

const pendingCount = computed(() => {
  const orders = orderStore.orders.filter(o => {
    if (isWarehouse.value) {
      return o.status === 'confirmed'
    }
    if (isManager.value) {
      return o.status === 'pending' || o.status === 'delivered' || 
             (o.status === 'shipped' && o.storeId === currentUser.value?.storeId)
    }
    return o.status === 'pending'
  })
  return orders.length
})

const issueCount = computed(() => {
  return orderStore.getMyPendingIssues(
    currentUser.value?.role || 'store_manager',
    currentUser.value?.storeId,
    currentUser.value?.id
  ).length
})

const handleMenuSelect = (index: string) => {
  router.push(index)
}

const handleCommand = (command: string) => {
  if (command === 'logout') {
    authStore.logout()
    router.push('/login')
  } else if (command === 'switch') {
    router.push('/login')
  }
}
</script>

<style scoped>
.layout-container {
  height: 100%;
}

.sidebar {
  background: #001529;
  display: flex;
  flex-direction: column;
}

.sidebar-header {
  padding: 20px;
  display: flex;
  align-items: center;
  border-bottom: 1px solid rgba(255, 255, 255, 0.1);
}

.sidebar-header .logo {
  font-size: 28px;
  margin-right: 10px;
}

.sidebar-header .brand {
  color: white;
  font-size: 18px;
  font-weight: 600;
}

.sidebar-menu {
  flex: 1;
  border-right: none;
  background: transparent;
}

.sidebar-menu :deep(.el-menu-item) {
  color: rgba(255, 255, 255, 0.7);
}

.sidebar-menu :deep(.el-menu-item:hover) {
  background: rgba(255, 255, 255, 0.1);
  color: white;
}

.sidebar-menu :deep(.el-menu-item.is-active) {
  background: #1890ff;
  color: white;
}

.menu-badge {
  margin-left: 5px;
}

.header {
  background: white;
  border-bottom: 1px solid #e8e8e8;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 24px;
}

.header-right {
  display: flex;
  align-items: center;
  gap: 20px;
}

.role-tag {
  padding: 4px 12px;
  border-radius: 20px;
  font-size: 13px;
  font-weight: 500;
}

.role-store-manager {
  background: #e6f7ff;
  color: #1890ff;
}

.role-planner {
  background: #f6ffed;
  color: #52c41a;
}

.role-warehouse {
  background: #fff7e6;
  color: #fa8c16;
}

.user-info {
  display: flex;
  align-items: center;
  cursor: pointer;
  padding: 5px 10px;
  border-radius: 6px;
  transition: background 0.3s;
}

.user-info:hover {
  background: #f5f5f5;
}

.user-info .avatar {
  font-size: 24px;
  margin-right: 8px;
}

.user-info .username {
  margin-right: 5px;
  color: #333;
}

.user-info .dropdown-icon {
  color: #999;
  font-size: 12px;
}

.main-content {
  background: #f0f2f5;
  padding: 24px;
  overflow-y: auto;
}

.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.2s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>
