// src/pages/LoginPage.tsx
import { useNavigate } from 'react-router-dom';
import { LayoutDashboard, Users, Headphones, Shield, ArrowRight } from 'lucide-react';
import { useAppStore, getRoleName } from '@/store/app.store';
import { Button } from '@/components/common/Button';
import { Card } from '@/components/common/Card';
import type { UserRole } from '@/types';
import { cn } from '@/lib/utils';

const roles: Array<{
  role: UserRole;
  icon: React.ComponentType<{ className?: string }>;
  description: string;
  features: string[];
  color: string;
}> = [
  {
    role: 'manager',
    icon: Shield,
    description: '全局数据监控与规则配置',
    features: ['全局看板', '考核规则配置', '培训计划管理', '跨角色协调'],
    color: 'from-blue-600 to-blue-800',
  },
  {
    role: 'dispatcher',
    icon: Users,
    description: '订单异常处理与骑手调度',
    features: ['超时判定', '补贴审核', '考核发起', '骑手信息查询'],
    color: 'from-amber-500 to-orange-600',
  },
  {
    role: 'customer_service',
    icon: Headphones,
    description: '用户申诉与退款处理',
    features: ['申诉处理', '退款审核', '问题转派', '订单查询'],
    color: 'from-green-500 to-emerald-600',
  },
];

export function LoginPage() {
  const navigate = useNavigate();
  const { login } = useAppStore();

  const handleLogin = (role: UserRole) => {
    login(role);
    navigate('/dashboard');
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-primary-800 via-primary-900 to-primary-950 flex items-center justify-center p-8">
      <div className="w-full max-w-5xl">
        <div className="text-center mb-12">
          <div className="inline-flex items-center justify-center w-16 h-16 bg-white/10 rounded-2xl mb-6">
            <LayoutDashboard className="w-8 h-8 text-white" />
          </div>
          <h1 className="text-3xl font-bold text-white mb-3">骑手考核与培训记录系统</h1>
          <p className="text-primary-300">整合订单、申诉、补贴、考核、培训全链路数据</p>
          <p className="text-primary-400 text-sm mt-1">实现从问题发现到培训跟进的完整业务闭环</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {roles.map(role => {
            const RoleIcon = role.icon;
            return (
              <Card
                key={role.role}
                className="group hover:shadow-xl transition-all duration-300 cursor-pointer overflow-hidden"
                onClick={() => handleLogin(role.role)}
                padding="none"
              >
                <div className={cn('h-2 bg-gradient-to-r', role.color)} />
                <div className="p-6">
                  <div className="flex items-start justify-between mb-4">
                    <div className={cn(
                      'w-12 h-12 rounded-xl flex items-center justify-center bg-gradient-to-br text-white',
                      role.color
                    )}>
                      <RoleIcon className="w-6 h-6" />
                    </div>
                    <ArrowRight className="w-5 h-5 text-gray-400 group-hover:text-primary-600 group-hover:translate-x-1 transition-all" />
                  </div>

                  <h3 className="text-lg font-bold text-gray-900 mb-1">
                    {getRoleName(role.role)}
                  </h3>
                  <p className="text-sm text-gray-500 mb-4">{role.description}</p>

                  <div className="space-y-2">
                    {role.features.map((feature, idx) => (
                      <div key={idx} className="flex items-center gap-2 text-sm text-gray-600">
                        <div className="w-1.5 h-1.5 rounded-full bg-gray-300" />
                        {feature}
                      </div>
                    ))}
                  </div>

                  <div className="mt-6 pt-4 border-t border-gray-100">
                    <Button
                      className={cn('w-full bg-gradient-to-r', role.color)}
                      onClick={(e) => {
                        e.stopPropagation();
                        handleLogin(role.role);
                      }}
                    >
                      进入系统
                      <ArrowRight className="w-4 h-4 ml-2" />
                    </Button>
                  </div>
                </div>
              </Card>
            );
          })}
        </div>

        <div className="mt-8 text-center">
          <p className="text-primary-400 text-sm">
            演示系统：点击上方角色卡片即可进入对应角色的工作界面
          </p>
          <p className="text-primary-500 text-xs mt-2">
            可在系统内通过顶部角色切换功能体验不同角色视角
          </p>
        </div>
      </div>
    </div>
  );
}

// src/pages/LoginPage.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { Music, Crown, Headphones, Wrench } from 'lucide-vue-next'
import { useAuthStore } from '@/stores/auth'
import { useNotificationStore } from '@/stores/notification'
import { USERS } from '@/types'
import type { UserRole } from '@/types'
import { cn } from '@/lib/utils'

const router = useRouter()
const authStore = useAuthStore()
const notificationStore = useNotificationStore()

const selectedRole = ref<UserRole | null>(null)
const isLoading = ref(false)

const roleCards: Array<{
  role: UserRole
  icon: typeof Crown
  name: string
  label: string
  password: string
  color: string
}> = [
  { role: 'boss', icon: Crown, name: USERS.boss.name, label: '门店老板', password: USERS.boss.password, color: 'from-amber-500/20 to-orange-500/20' },
  { role: 'consultant', icon: Headphones, name: USERS.consultant.name, label: '租赁顾问', password: USERS.consultant.password, color: 'from-blue-500/20 to-indigo-500/20' },
  { role: 'repair', icon: Wrench, name: USERS.repair.name, label: '维修师傅', password: USERS.repair.password, color: 'from-emerald-500/20 to-teal-500/20' },
]

const passwords = ref<Record<UserRole, string>>({
  boss: '',
  consultant: '',
  repair: '',
})

async function handleCardClick(role: UserRole, password: string) {
  if (isLoading.value) return
  selectedRole.value = role
  passwords.value[role] = password
  isLoading.value = true

  await new Promise(r => setTimeout(r, 400))

  const success = authStore.login(role, password)
  if (success) {
    notificationStore.showToast(`欢迎回来，${USERS[role].name}`, 'success')
    router.push('/dashboard')
  } else {
    notificationStore.showToast('登录失败，请重试', 'error')
    passwords.value[role] = ''
    selectedRole.value = null
    isLoading.value = false
  }
}
</script>

<template>
  <div class="min-h-screen bg-bg-primary flex items-center justify-center relative overflow-hidden">
    <div class="absolute top-[-20%] left-[-10%] w-[500px] h-[500px] rounded-full bg-accent/5 blur-[120px] pointer-events-none" />
    <div class="absolute bottom-[-15%] right-[-5%] w-[400px] h-[400px] rounded-full bg-purple-500/5 blur-[100px] pointer-events-none" />
    <div class="absolute top-[30%] right-[15%] w-[200px] h-[200px] rounded-full bg-blue-500/5 blur-[80px] pointer-events-none" />

    <div class="w-full max-w-md mx-4 bg-bg-secondary rounded-xl shadow-2xl shadow-black/40 relative z-10 animate-fade-in">
      <div class="px-8 pt-10 pb-6 text-center">
        <div class="inline-flex items-center justify-center w-14 h-14 rounded-xl bg-accent/10 mb-5">
          <Music :size="28" class="text-accent" />
        </div>
        <h1 class="font-serif-title text-3xl text-txt-primary tracking-wide">乐器租赁</h1>
        <p class="text-txt-secondary mt-2 text-sm">订单链路追踪系统</p>
      </div>

      <div class="px-6 pb-8 space-y-3">
        <div
          v-for="card in roleCards"
          :key="card.role"
          @click="handleCardClick(card.role, card.password)"
          :class="cn(
            'relative flex items-center gap-4 p-4 rounded-xl border cursor-pointer transition-all duration-300',
            selectedRole === card.role
              ? 'border-accent shadow-[0_0_20px_rgba(232,168,56,0.25)] bg-gradient-to-r ' + card.color
              : 'border-border bg-bg-tertiary/50 hover:border-accent/50 hover:shadow-[0_0_12px_rgba(232,168,56,0.12)]'
          )"
        >
          <div
            :class="cn(
              'flex-shrink-0 w-11 h-11 rounded-lg flex items-center justify-center transition-colors duration-300',
              selectedRole === card.role ? 'bg-accent/20' : 'bg-bg-tertiary'
            )"
          >
            <component
              :is="card.icon"
              :size="22"
              :class="selectedRole === card.role ? 'text-accent' : 'text-txt-muted'"
            />
          </div>

          <div class="flex-1 min-w-0">
            <p class="text-sm font-medium text-txt-primary">{{ card.label }}</p>
            <p class="text-xs text-txt-muted mt-0.5">{{ card.name }}</p>
          </div>

          <div class="flex-shrink-0 w-28">
            <input
              type="password"
              :value="passwords[card.role]"
              readonly
              placeholder="密码"
              class="w-full bg-bg-primary/60 border border-border rounded-lg px-3 py-1.5 text-sm text-txt-primary placeholder:text-txt-muted/50 focus:outline-none focus:border-accent/50 transition-colors"
            />
          </div>

          <div
            v-if="selectedRole === card.role && isLoading"
            class="absolute inset-0 flex items-center justify-center bg-bg-secondary/60 rounded-xl"
          >
            <div class="w-5 h-5 border-2 border-accent border-t-transparent rounded-full animate-spin" />
          </div>
        </div>
      </div>

      <div class="px-8 pb-6 text-center">
        <p class="text-xs text-txt-muted">点击角色卡片即可快速登录</p>
      </div>
    </div>
  </div>
</template>
