// watch-service-system/components/common/RoleSwitcher.vue
<template>
  <div class="relative">
    <button
      @click="isOpen = !isOpen"
      class="flex items-center space-x-2 px-3 py-2 rounded-lg bg-white border border-gray-200 hover:bg-gray-50 transition-colors"
    >
      <div class="w-8 h-8 rounded-full bg-primary-100 flex items-center justify-center">
        <Icon :icon="roleIcon" class="w-4 h-4 text-primary-700" />
      </div>
      <div class="text-left">
        <p class="text-sm font-medium text-gray-900">{{ userName }}</p>
        <p class="text-xs text-gray-500">{{ currentRoleLabel }}</p>
      </div>
      <Icon icon="mdi:chevron-down" class="w-4 h-4 text-gray-400" />
    </button>
    
    <Transition
      enter-active-class="transition ease-out duration-100"
      enter-from-class="transform opacity-0 scale-95"
      enter-to-class="transform opacity-100 scale-100"
      leave-active-class="transition ease-in duration-75"
      leave-from-class="transform opacity-100 scale-100"
      leave-to-class="transform opacity-0 scale-95"
    >
      <div
        v-if="isOpen"
        class="absolute right-0 mt-2 w-56 rounded-xl bg-white shadow-lg border border-gray-100 z-50 overflow-hidden"
      >
        <div class="px-4 py-3 bg-gray-50 border-b border-gray-100">
          <p class="text-xs font-medium text-gray-500 uppercase tracking-wider">切换角色</p>
        </div>
        <div class="py-2">
          <button
            v-for="role in roles"
            :key="role.value"
            @click="selectRole(role.value)"
            :class="[
              'w-full flex items-center px-4 py-3 text-left hover:bg-gray-50 transition-colors',
              currentRole === role.value ? 'bg-primary-50' : ''
            ]"
          >
            <div :class="[
              'w-10 h-10 rounded-full flex items-center justify-center mr-3',
              currentRole === role.value ? 'bg-primary-100' : 'bg-gray-100'
            ]">
              <Icon :icon="role.icon" :class="[
                'w-5 h-5',
                currentRole === role.value ? 'text-primary-700' : 'text-gray-500'
              ]" />
            </div>
            <div>
              <p :class="[
                'text-sm font-medium',
                currentRole === role.value ? 'text-primary-700' : 'text-gray-900'
              ]">{{ role.label }}</p>
              <p class="text-xs text-gray-500">{{ role.desc }}</p>
            </div>
            <Icon
              v-if="currentRole === role.value"
              icon="mdi:check"
              class="w-5 h-5 text-primary-600 ml-auto"
            />
          </button>
        </div>
      </div>
    </Transition>
    
    <div v-if="isOpen" class="fixed inset-0 z-40" @click="isOpen = false"></div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import type { UserRole } from '~/types/workorder';

const { currentRole, currentRoleLabel, userName, setRole } = useRole();

const isOpen = ref(false);

const roleIcon = computed(() => {
  const icons: Record<UserRole, string> = {
    manager: 'mdi:account-tie',
    consultant: 'mdi:account-headset',
    technician: 'mdi:hammer-wrench',
  };
  return icons[currentRole.value];
});

const roles = [
  { value: 'manager' as UserRole, label: '售后经理', desc: '审批报价、查看全局', icon: 'mdi:account-tie' },
  { value: 'consultant' as UserRole, label: '接件顾问', desc: '登记寄修、跟进客户', icon: 'mdi:account-headset' },
  { value: 'technician' as UserRole, label: '维修技师', desc: '检测维修、更新进度', icon: 'mdi:hammer-wrench' },
];

function selectRole(role: UserRole) {
  setRole(role);
  isOpen.value = false;
}
</script>

// golf-equipment-tracker/src/components/layout/RoleSwitcher.tsx
"use client";

import React, { useState } from "react";
import { ChevronDown, User } from "lucide-react";
import { useApp } from "@/lib/context/AppContext";
import { getRoleLabel } from "@/lib/mockData";
import type { UserRole } from "@/types";

export const RoleSwitcher: React.FC = () => {
  const { currentUser, switchRole } = useApp();
  const [isOpen, setIsOpen] = useState(false);

  const roles: { value: UserRole; label: string }[] = [
    { value: "reception", label: "前台" },
    { value: "coach", label: "教练" },
    { value: "manager", label: "经理" },
  ];

  return (
    <div className="relative">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="flex items-center space-x-2 px-3 py-2 rounded-lg border border-gray-200 hover:bg-gray-50 transition-colors"
      >
        <div className="w-8 h-8 bg-blue-100 rounded-full flex items-center justify-center">
          <User className="w-4 h-4 text-blue-600" />
        </div>
        <div className="text-left hidden sm:block">
          <p className="text-sm font-medium text-gray-900">{currentUser.name}</p>
          <p className="text-xs text-gray-500">{getRoleLabel(currentUser.role)}</p>
        </div>
        <ChevronDown className="w-4 h-4 text-gray-400" />
      </button>

      {isOpen && (
        <>
          <div
            className="fixed inset-0 z-10"
            onClick={() => setIsOpen(false)}
          />
          <div className="absolute right-0 mt-2 w-48 bg-white rounded-lg shadow-lg border border-gray-200 z-20 py-1">
            <div className="px-3 py-2 border-b border-gray-100">
              <p className="text-xs font-medium text-gray-500">切换角色</p>
            </div>
            {roles.map((role) => (
              <button
                key={role.value}
                onClick={() => {
                  switchRole(role.value);
                  setIsOpen(false);
                }}
                className={`w-full px-3 py-2 text-left text-sm hover:bg-gray-50 flex items-center justify-between ${
                  currentUser.role === role.value
                    ? "bg-blue-50 text-blue-700"
                    : "text-gray-700"
                }`}
              >
                <span>{role.label}</span>
                {currentUser.role === role.value && (
                  <span className="w-2 h-2 bg-blue-500 rounded-full" />
                )}
              </button>
            ))}
          </div>
        </>
      )}
    </div>
  );
};
