// frontend/src/components/Layout.vue
<template>
  <div class="flex h-screen bg-gray-100">
    <aside class="w-64 bg-white shadow-lg flex flex-col">
      <div class="p-6 border-b border-gray-100">
        <div class="flex items-center gap-3">
          <div class="w-10 h-10 bg-primary-100 rounded-lg flex items-center justify-center">
            <component :is="ClipboardList" class="w-5 h-5 text-primary-600" />
          </div>
          <div>
            <h1 class="font-bold text-gray-800">客诉管理</h1>
            <p class="text-xs text-gray-500">赔付与复检系统</p>
          </div>
        </div>
      </div>

      <nav class="flex-1 p-4 space-y-1">
        <router-link
          v-for="item in menuItems"
          :key="item.path"
          :to="item.path"
          class="flex items-center gap-3 px-4 py-3 rounded-lg text-gray-600 hover:bg-gray-50 hover:text-primary-600 transition-colors"
          :class="{ 'bg-primary-50 text-primary-600': isActive(item.path) }"
        >
          <component :is="item.icon" class="w-5 h-5" />
          <span class="font-medium">{{ item.label }}</span>
        </router-link>
      </nav>

      <div class="p-4 border-t border-gray-100">
        <div class="flex items-center justify-between mb-4">
          <div class="flex items-center gap-3">
            <div class="w-10 h-10 bg-primary-100 rounded-full flex items-center justify-center">
              <span class="text-primary-600 font-semibold">{{ authStore.userName?.charAt(0) }}</span>
            </div>
            <div>
              <p class="font-medium text-gray-800 text-sm">{{ authStore.userName }}</p>
              <p class="text-xs text-gray-500">{{ ROLE_LABELS[authStore.userRole!] }}</p>
            </div>
          </div>
        </div>
        <el-button type="danger" size="small" class="w-full" @click="handleLogout">
          <component :is="LogOut" class="w-4 h-4 mr-1" />
          退出登录
        </el-button>
      </div>
    </aside>

    <main class="flex-1 flex flex-col overflow-hidden">
      <header class="bg-white shadow-sm px-8 py-4">
        <div class="flex items-center justify-between">
          <h2 class="text-xl font-semibold text-gray-800">{{ currentTitle }}</h2>
          <div class="flex items-center gap-4">
            <slot name="header-actions"></slot>
          </div>
        </div>
      </header>

      <div class="flex-1 overflow-auto p-6">
        <router-view v-slot="{ Component }">
          <transition name="fade" mode="out-in">
            <component :is="Component" />
          </transition>
        </router-view>
      </div>
    </main>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import {
  LayoutDashboard,
  FilePlus,
  CheckSquare,
  DollarSign,
  History,
  ClipboardList,
  LogOut,
} from 'lucide-vue-next';
import { useAuthStore } from '../stores/auth';
import { ROLE_LABELS } from '../types';

const route = useRoute();
const router = useRouter();
const authStore = useAuthStore();

const menuItems = computed(() => {
  const items = [
    { path: '/dashboard', label: '批量复核面板', icon: LayoutDashboard },
  ];

  if (authStore.hasRole(['manager', 'picker'])) {
    items.push({ path: '/complaint/new', label: '新建客诉', icon: FilePlus });
  }

  if (authStore.hasRole(['manager', 'accountant'])) {
    items.push({ path: '/compensation', label: '赔付审批', icon: CheckSquare });
    items.push({ path: '/payment', label: '回款跟踪', icon: DollarSign });
  }

  items.push({ path: '/history', label: '历史记录', icon: History });

  return items;
});

const currentTitle = computed(() => route.meta?.title || '批量复核面板');

function isActive(path: string) {
  return route.path.startsWith(path);
}

function handleLogout() {
  authStore.logout();
  router.push('/login');
}
</script>

// src/components/Layout.tsx
import { ReactNode } from 'react';
import { useRouter } from 'next/router';
import { 
  LayoutDashboard, 
  Users, 
  Calendar, 
  AlertTriangle, 
  LogOut,
  FileText,
  User
} from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { roleLabels } from '../utils/format';

interface NavItem {
  label: string;
  icon: ReactNode;
  href: string;
  roles?: string[];
}

export default function Layout({ children }: { children: ReactNode }) {
  const { user, logout } = useAuth();
  const router = useRouter();

  const navItems: NavItem[] = [
    { label: '仪表板', icon: <LayoutDashboard size={20} />, href: '/dashboard' },
    { label: '学生列表', icon: <Users size={20} />, href: '/students' },
    { label: '日历视图', icon: <Calendar size={20} />, href: '/calendar' },
    { label: '问题追踪', icon: <AlertTriangle size={20} />, href: '/issues' },
  ];

  async function handleLogout() {
    await logout();
    router.push('/login');
  }

  return (
    <div className="min-h-screen flex">
      <aside className="w-64 bg-white border-r border-gray-200 flex flex-col">
        <div className="p-4 border-b border-gray-200">
          <h1 className="text-xl font-bold text-primary-600">留学服务系统</h1>
          <p className="text-xs text-gray-500 mt-1">文书流转与截点提醒</p>
        </div>

        <nav className="flex-1 p-4 space-y-1">
          {navItems.map((item) => (
            <button
              key={item.href}
              onClick={() => router.push(item.href)}
              className={`w-full flex items-center gap-3 px-3 py-2 rounded-lg text-sm transition-colors ${
                router.pathname === item.href
                  ? 'bg-primary-50 text-primary-700'
                  : 'text-gray-600 hover:bg-gray-50'
              }`}
            >
              {item.icon}
              {item.label}
            </button>
          ))}
        </nav>

        <div className="p-4 border-t border-gray-200">
          <div className="flex items-center gap-3 mb-3">
            <div className="w-10 h-10 rounded-full bg-primary-100 flex items-center justify-center">
              <User size={20} className="text-primary-600" />
            </div>
            <div>
              <p className="text-sm font-medium text-gray-900">{user?.name}</p>
              <p className="text-xs text-gray-500">{roleLabels[user?.role || '']}</p>
            </div>
          </div>
          <button
            onClick={handleLogout}
            className="w-full flex items-center gap-2 px-3 py-2 text-sm text-gray-600 hover:bg-gray-50 rounded-lg"
          >
            <LogOut size={18} />
            退出登录
          </button>
        </div>
      </aside>

      <main className="flex-1 overflow-auto">
        {children}
      </main>
    </div>
  );
}
