// watch-after-sales/frontend/src/components/StatusBadge.tsx
"use client";

import { STATUS_LABELS, STATUS_COLORS } from "@/lib/utils";

interface StatusBadgeProps {
  status: string;
}

export default function StatusBadge({ status }: StatusBadgeProps) {
  const label = STATUS_LABELS[status] || status;
  const color = STATUS_COLORS[status] || "bg-gray-100 text-gray-700";

  return (
    <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${color}`}>
      {label}
    </span>
  );
}

// src/components/StatusBadge.vue
<script setup lang="ts">
import type { OrderStatus } from '@/types'
import { ORDER_STATUS_LABELS, ORDER_STATUS_COLORS } from '@/types'
import { cn } from '@/lib/utils'

const props = defineProps<{
  status: OrderStatus
}>()
</script>

<template>
  <span
    :class="cn(
      'inline-flex items-center px-2 py-0.5 rounded text-xs font-medium',
      ORDER_STATUS_COLORS[props.status]
    )"
  >
    {{ ORDER_STATUS_LABELS[props.status] }}
  </span>
</template>
