// src/components/ui/Timeline.tsx
import { format } from 'date-fns';
import { zhCN } from 'date-fns/locale';

interface TimelineItem {
  id: string;
  action: string;
  userName: string;
  createdAt: string;
  oldValue?: string;
  newValue?: string;
}

interface TimelineProps {
  items: TimelineItem[];
}

export function Timeline({ items }: TimelineProps) {
  return (
    <div className="relative">
      <div className="absolute left-4 top-0 bottom-0 w-px bg-gray-200" />
      <div className="space-y-4">
        {items.map((item) => (
          <div key={item.id} className="relative pl-10">
            <div className="absolute left-2 w-5 h-5 bg-blue-100 rounded-full border-2 border-blue-500 flex items-center justify-center">
              <div className="w-2 h-2 bg-blue-500 rounded-full" />
            </div>
            <div className="bg-gray-50 rounded-lg p-3">
              <div className="flex items-center justify-between">
                <span className="font-medium text-gray-900">{item.action}</span>
                <span className="text-xs text-gray-500">
                  {format(new Date(item.createdAt), 'MM-dd HH:mm', { locale: zhCN })}
                </span>
              </div>
              <p className="text-sm text-gray-600 mt-1">操作人：{item.userName}</p>
              {item.oldValue && item.newValue && (
                <p className="text-sm text-gray-500 mt-1">
                  {item.oldValue} → <span className="text-blue-600">{item.newValue}</span>
                </p>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

// src/components/Timeline.vue
<script setup lang="ts">
export interface TimelineItem {
  title: string
  subtitle?: string
  detail?: string
  timestamp?: string
  color?: 'green' | 'amber' | 'red' | 'blue' | 'gray'
}

const props = defineProps<{
  items: TimelineItem[]
}>()

const dotColor = (color?: string) => {
  const map: Record<string, string> = {
    green: 'bg-status-green',
    amber: 'bg-accent-600',
    red: 'bg-danger-600',
    blue: 'bg-blue-500',
    gray: 'bg-status-gray',
  }
  return map[color || 'gray'] || map.gray
}
</script>

<template>
  <div class="relative">
    <div
      v-for="(item, idx) in items"
      :key="idx"
      class="flex gap-3 pb-4 last:pb-0"
    >
      <div class="flex flex-col items-center">
        <div :class="dotColor(item.color)" class="w-2.5 h-2.5 rounded-full mt-1.5 shrink-0" />
        <div v-if="idx < items.length - 1" class="w-px flex-1 bg-border mt-1" />
      </div>
      <div class="flex-1 min-w-0 pb-1">
        <div class="text-sm font-medium text-text-primary">{{ item.title }}</div>
        <div v-if="item.subtitle" class="text-xs text-text-secondary mt-0.5">{{ item.subtitle }}</div>
        <div v-if="item.detail" class="text-xs text-text-muted mt-0.5">{{ item.detail }}</div>
        <div v-if="item.timestamp" class="text-xs text-text-muted mt-0.5">{{ item.timestamp }}</div>
      </div>
    </div>
  </div>
</template>
