// runner-platform/frontend/src/routes/login/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { api } from '$lib/api';
	import { setAuth } from '$lib/stores/auth';

	let username = '';
	let password = '';
	let error = '';
	let loading = false;

	async function handleLogin() {
		error = '';
		loading = true;
		try {
			const result = await api.login(username, password);
			setAuth(result.token, result.user);
			goto('/orders');
		} catch (e: any) {
			error = e.message;
		} finally {
			loading = false;
		}
	}
</script>

<div class="min-h-screen flex items-center justify-center bg-gradient-to-br from-blue-600 to-purple-700">
	<div class="bg-white rounded-xl shadow-2xl p-8 w-full max-w-md">
		<div class="text-center mb-8">
			<h1 class="text-3xl font-bold text-gray-900 mb-2">🚴 跑腿平台</h1>
			<p class="text-gray-500">订单派发与超时申诉系统</p>
		</div>

		<form on:submit|preventDefault={handleLogin} class="space-y-6">
			<div>
				<label class="block text-sm font-medium text-gray-700 mb-2">用户名</label>
				<input
					type="text"
					bind:value={username}
					class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
					placeholder="请输入用户名"
					required
				/>
			</div>

			<div>
				<label class="block text-sm font-medium text-gray-700 mb-2">密码</label>
				<input
					type="password"
					bind:value={password}
					class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
					placeholder="请输入密码"
					required
				/>
			</div>

			{#if error}
				<div class="p-3 bg-red-50 border border-red-200 rounded-lg text-red-600 text-sm">
					{error}
				</div>
			{/if}

			<button
				type="submit"
				disabled={loading}
				class="w-full py-3 bg-blue-600 text-white font-medium rounded-lg hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
			>
				{loading ? '登录中...' : '登 录'}
			</button>
		</form>

		<div class="mt-6 pt-6 border-t border-gray-100">
			<p class="text-xs text-gray-500 mb-3">测试账号（密码均为 123456）：</p>
			<div class="grid grid-cols-2 gap-2 text-xs">
				<div class="p-2 bg-gray-50 rounded"><span class="font-medium">admin</span> - 运营经理</div>
				<div class="p-2 bg-gray-50 rounded"><span class="font-medium">dispatch_zhang</span> - 调度</div>
				<div class="p-2 bg-gray-50 rounded"><span class="font-medium">cs_li</span> - 客服</div>
				<div class="p-2 bg-gray-50 rounded"><span class="font-medium">runner_wang</span> - 骑手</div>
			</div>
		</div>
	</div>
</div>

// frontend/src/pages/Login.tsx
import { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import { useAuthStore } from '../store/authStore';
import { ROUTES } from '../lib/routes';

export default function Login() {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const { login, isLoading, error, user } = useAuthStore();
  const router = useRouter();

  useEffect(() => {
    if (user) {
      router.push(ROUTES.HOME);
    }
  }, [user, router]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      await login(username, password);
      router.push(ROUTES.HOME);
    } catch (err) {
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-primary-50 to-primary-100 flex items-center justify-center p-4">
      <div className="bg-white rounded-2xl shadow-xl p-8 w-full max-w-md">
        <div className="text-center mb-8">
          <div className="w-16 h-16 bg-primary-500 rounded-full flex items-center justify-center mx-auto mb-4">
            <svg className="w-8 h-8 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" />
            </svg>
          </div>
          <h1 className="text-2xl font-bold text-gray-800">地方剧院票务系统</h1>
          <p className="text-gray-500 mt-2">团单管理与退改审核平台</p>
        </div>

        <form onSubmit={handleSubmit} className="space-y-6">
          {error && (
            <div className="bg-red-50 border border-red-200 text-red-600 px-4 py-3 rounded-lg text-sm">
              {error}
            </div>
          )}

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              用户名
            </label>
            <input
              type="text"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent outline-none transition"
              placeholder="请输入用户名"
              required
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              密码
            </label>
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent outline-none transition"
              placeholder="请输入密码"
              required
            />
          </div>

          <button
            type="submit"
            disabled={isLoading}
            className="w-full bg-primary-500 hover:bg-primary-600 text-white font-medium py-3 px-4 rounded-lg transition disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {isLoading ? '登录中...' : '登 录'}
          </button>
        </form>

        <div className="mt-6 pt-6 border-t border-gray-200">
          <p className="text-sm text-gray-500 text-center mb-3">测试账号（密码均为 123456）</p>
          <div className="grid grid-cols-3 gap-2 text-xs text-center">
            <div className="bg-gray-50 rounded-lg p-2">
              <div className="font-medium text-gray-700">manager</div>
              <div className="text-gray-500">剧院经理</div>
            </div>
            <div className="bg-gray-50 rounded-lg p-2">
              <div className="font-medium text-gray-700">ticket</div>
              <div className="text-gray-500">票务主管</div>
            </div>
            <div className="bg-gray-50 rounded-lg p-2">
              <div className="font-medium text-gray-700">backend</div>
              <div className="text-gray-500">后台统筹</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
