// frontend/src/components/StatusBadge.vue
<script setup lang="ts">
import { computed } from 'vue'
import { cn } from '@/lib/utils'

const props = defineProps<{
  status: string
  type?: 'order' | 'pickup' | 'remake' | 'refund' | 'review' | 'schedule'
}>()

const statusConfig = computed(() => {
  const configs: Record<string, Record<string, { label: string; class: string }>> = {
    order: {
      pending: { label: '待确认', class: 'bg-yellow-100 text-yellow-800 border-yellow-200' },
      confirmed: { label: '已确认', class: 'bg-blue-100 text-blue-800 border-blue-200' },
      scheduled: { label: '已排产', class: 'bg-purple-100 text-purple-800 border-purple-200' },
      producing: { label: '制作中', class: 'bg-bakery-100 text-bakery-700 border-bakery-300' },
      completed: { label: '已完成', class: 'bg-green-100 text-green-800 border-green-200' },
      exception: { label: '异常', class: 'bg-accent-light text-accent border-accent' },
      refunded: { label: '已退款', class: 'bg-red-100 text-red-700 border-red-200' },
    },
    pickup: {
      waiting: { label: '待取货', class: 'bg-yellow-100 text-yellow-800 border-yellow-200' },
      notified: { label: '已通知', class: 'bg-blue-100 text-blue-800 border-blue-200' },
      verified: { label: '已核销', class: 'bg-green-100 text-green-800 border-green-200' },
      completed: { label: '已完成', class: 'bg-green-100 text-green-800 border-green-200' },
    },
    remake: {
      open: { label: '待处理', class: 'bg-accent-light text-accent border-accent' },
      scheduled: { label: '已排产', class: 'bg-purple-100 text-purple-800 border-purple-200' },
      producing: { label: '重做中', class: 'bg-bakery-100 text-bakery-700 border-bakery-300' },
      completed: { label: '已完成', class: 'bg-green-100 text-green-800 border-green-200' },
      closed: { label: '已关闭', class: 'bg-gray-100 text-gray-600 border-gray-200' },
    },
    refund: {
      requested: { label: '待审核', class: 'bg-yellow-100 text-yellow-800 border-yellow-200' },
      tracing: { label: '追溯中', class: 'bg-blue-100 text-blue-800 border-blue-200' },
      approved: { label: '已完成', class: 'bg-green-100 text-green-800 border-green-200' },
      completed: { label: '已完成', class: 'bg-green-100 text-green-800 border-green-200' },
      rejected: { label: '已拒绝', class: 'bg-gray-100 text-gray-600 border-gray-200' },
    },
    review: {
      pending: { label: '待复核', class: 'bg-yellow-100 text-yellow-800 border-yellow-200' },
      approved: { label: '已通过', class: 'bg-green-100 text-green-800 border-green-200' },
      rejected: { label: '已拒绝', class: 'bg-gray-100 text-gray-600 border-gray-200' },
    },
    schedule: {
      pending: { label: '待生产', class: 'bg-yellow-100 text-yellow-800 border-yellow-200' },
      producing: { label: '生产中', class: 'bg-bakery-100 text-bakery-700 border-bakery-300' },
      completed: { label: '已完成', class: 'bg-green-100 text-green-800 border-green-200' },
    },
  }
  const type = props.type || 'order'
  return configs[type]?.[props.status] || { label: props.status, class: 'bg-gray-100 text-gray-600 border-gray-200' }
})
</script>

<template>
  <span
    class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium border"
    :class="cn(statusConfig.class)"
  >
    {{ statusConfig.label }}
  </span>
</template>

// src/components/common/StatusBadge.tsx
import React from 'react';
import type { OrderStatus } from '../../types';
import { cn } from '../../lib/utils';

interface StatusBadgeProps {
  status: OrderStatus;
  className?: string;
}

const statusConfig: Record<OrderStatus, { label: string; className: string }> = {
  pending_review: {
    label: '待审核',
    className: 'bg-yellow-100 text-yellow-800 border-yellow-200',
  },
  reviewed: {
    label: '已审核',
    className: 'bg-blue-100 text-blue-800 border-blue-200',
  },
  scheduled: {
    label: '已排期',
    className: 'bg-purple-100 text-purple-800 border-purple-200',
  },
  in_production: {
    label: '生产中',
    className: 'bg-bakery-matcha/20 text-bakery-matcha border-bakery-matcha/30',
  },
  completed: {
    label: '已完成',
    className: 'bg-green-100 text-green-800 border-green-200',
  },
  change_requested: {
    label: '申请改单',
    className: 'bg-orange-100 text-orange-800 border-orange-200',
  },
  refund_requested: {
    label: '申请退款',
    className: 'bg-red-100 text-red-800 border-red-200',
  },
  refunded: {
    label: '已退款',
    className: 'bg-gray-100 text-gray-800 border-gray-200',
  },
  cancelled: {
    label: '已取消',
    className: 'bg-gray-100 text-gray-500 border-gray-200',
  },
};

export const StatusBadge: React.FC<StatusBadgeProps> = ({ status, className }) => {
  const config = statusConfig[status];
  
  return (
    <span
      className={cn(
        'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium border',
        config.className,
        className
      )}
    >
      {config.label}
    </span>
  );
};
