// frontend/src/pages/Dashboard.jsx
import { useState, useEffect } from 'react'
import { Link } from 'react-router-dom'
import {
  Clock,
  XCircle,
  AlertCircle,
  Calendar,
  Package,
  Ticket,
  MessageSquare,
  ChevronRight,
} from 'lucide-react'
import { dashboardAPI } from '../utils/api'

export default function Dashboard() {
  const [stats, setStats] = useState(null)
  const [pendingItems, setPendingItems] = useState(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    fetchDashboardData()
  }, [])

  const fetchDashboardData = async () => {
    try {
      const [statsRes, itemsRes] = await Promise.all([
        dashboardAPI.getStats(),
        dashboardAPI.getPendingItems(),
      ])
      setStats(statsRes.data)
      setPendingItems(itemsRes.data)
    } catch (error) {
      console.error('Failed to fetch dashboard data:', error)
    } finally {
      setLoading(false)
    }
  }

  const statCards = stats ? [
    { label: '待处理反馈', value: stats.pending_feedbacks, color: 'yellow', icon: MessageSquare, link: '/feedbacks?status=pending' },
    { label: '已驳回反馈', value: stats.rejected_feedbacks, color: 'red', icon: XCircle, link: '/feedbacks?status=rejected' },
    { label: '待确认排班', value: stats.pending_schedules, color: 'blue', icon: Calendar, link: '/schedules?status=pending' },
    { label: '待确认流转', value: stats.pending_transfers, color: 'purple', icon: Package, link: '/exhibits' },
    { label: '待核销门票', value: stats.pending_tickets, color: 'green', icon: Ticket, link: '/activities' },
    { label: '需回查事项', value: stats.needs_review_count, color: 'orange', icon: AlertCircle, link: '/review' },
  ] : []

  const getStatusBadge = (status) => {
    const statusMap = {
      pending: 'status-pending',
      processing: 'status-processing',
      resolved: 'status-resolved',
      rejected: 'status-rejected',
      confirmed: 'status-confirmed',
    }
    return `status-badge ${statusMap[status] || 'status-pending'}`
  }

  const formatDate = (dateStr) => {
    return new Date(dateStr).toLocaleDateString('zh-CN', {
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    })
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-gray-500">加载中...</div>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">运营仪表盘</h1>
        <p className="text-gray-500 mt-1">查看今日待处理事项和运营概览</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6 gap-4">
        {statCards.map((card, index) => {
          const Icon = card.icon
          return (
            <Link
              key={index}
              to={card.link}
              className="card hover:shadow-md transition-shadow"
            >
              <div className="card-body">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm text-gray-500">{card.label}</p>
                    <p className="text-3xl font-bold mt-1">{card.value}</p>
                  </div>
                  <div className={`p-3 rounded-lg bg-${card.color}-100`}>
                    <Icon className={`text-${card.color}-600`} size={24} />
                  </div>
                </div>
              </div>
            </Link>
          )
        })}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="card">
          <div className="card-header flex items-center justify-between">
            <h2 className="text-lg font-semibold flex items-center gap-2">
              <Clock className="text-yellow-500" size={20} />
              待处理反馈
            </h2>
            <Link to="/feedbacks" className="text-museum-600 text-sm flex items-center hover:underline">
              查看全部 <ChevronRight size={16} />
            </Link>
          </div>
          <div className="card-body">
            <div className="space-y-3">
              {pendingItems?.pending_feedbacks?.length > 0 ? (
                pendingItems.pending_feedbacks.slice(0, 5).map((feedback) => (
                  <Link
                    key={feedback.id}
                    to={`/feedbacks/${feedback.id}`}
                    className="block p-3 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors"
                  >
                    <div className="flex items-start justify-between">
                      <div className="flex-1">
                        <p className="font-medium text-gray-900">{feedback.title}</p>
                        <p className="text-sm text-gray-500 mt-1">{feedback.visitor_name || '匿名'}</p>
                      </div>
                      <span className={getStatusBadge(feedback.status)}>
                        {feedback.status === 'pending' ? '待处理' : '处理中'}
                      </span>
                    </div>
                  </Link>
                ))
              ) : (
                <p className="text-center text-gray-500 py-4">暂无待处理反馈</p>
              )}
            </div>
          </div>
        </div>

        <div className="card">
          <div className="card-header flex items-center justify-between">
            <h2 className="text-lg font-semibold flex items-center gap-2">
              <XCircle className="text-red-500" size={20} />
              已驳回反馈
            </h2>
            <Link to="/feedbacks?status=rejected" className="text-museum-600 text-sm flex items-center hover:underline">
              查看全部 <ChevronRight size={16} />
            </Link>
          </div>
          <div className="card-body">
            <div className="space-y-3">
              {pendingItems?.rejected_feedbacks?.length > 0 ? (
                pendingItems.rejected_feedbacks.slice(0, 5).map((feedback) => (
                  <Link
                    key={feedback.id}
                    to={`/feedbacks/${feedback.id}`}
                    className="block p-3 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors"
                  >
                    <div className="flex items-start justify-between">
                      <div className="flex-1">
                        <p className="font-medium text-gray-900">{feedback.title}</p>
                        <p className="text-sm text-gray-500 mt-1">{formatDate(feedback.created_at)}</p>
                      </div>
                      <span className="status-badge status-rejected">已驳回</span>
                    </div>
                  </Link>
                ))
              ) : (
                <p className="text-center text-gray-500 py-4">暂无已驳回反馈</p>
              )}
            </div>
          </div>
        </div>

        <div className="card">
          <div className="card-header flex items-center justify-between">
            <h2 className="text-lg font-semibold flex items-center gap-2">
              <AlertCircle className="text-orange-500" size={20} />
              需回查事项
            </h2>
            <Link to="/review" className="text-museum-600 text-sm flex items-center hover:underline">
              查看全部 <ChevronRight size={16} />
            </Link>
          </div>
          <div className="card-body">
            <div className="space-y-3">
              {pendingItems?.needs_review?.length > 0 ? (
                pendingItems.needs_review.slice(0, 5).map((feedback) => (
                  <Link
                    key={feedback.id}
                    to={`/feedbacks/${feedback.id}`}
                    className="block p-3 bg-orange-50 rounded-lg hover:bg-orange-100 transition-colors"
                  >
                    <div className="flex items-start justify-between">
                      <div className="flex-1">
                        <p className="font-medium text-gray-900">{feedback.title}</p>
                        <p className="text-sm text-orange-600 mt-1">{feedback.review_notes || '需要回查'}</p>
                      </div>
                      <AlertCircle className="text-orange-500" size={18} />
                    </div>
                  </Link>
                ))
              ) : (
                <p className="text-center text-gray-500 py-4">暂无需回查事项</p>
              )}
            </div>
          </div>
        </div>

        <div className="card">
          <div className="card-header flex items-center justify-between">
            <h2 className="text-lg font-semibold flex items-center gap-2">
              <Package className="text-purple-500" size={20} />
              待确认展品流转
            </h2>
            <Link to="/exhibits" className="text-museum-600 text-sm flex items-center hover:underline">
              查看全部 <ChevronRight size={16} />
            </Link>
          </div>
          <div className="card-body">
            <div className="space-y-3">
              {pendingItems?.pending_transfers?.length > 0 ? (
                pendingItems.pending_transfers.slice(0, 5).map((transfer) => (
                  <div
                    key={transfer.id}
                    className="p-3 bg-gray-50 rounded-lg"
                  >
                    <div className="flex items-start justify-between">
                      <div className="flex-1">
                        <p className="font-medium text-gray-900">{transfer.from_location} → {transfer.to_location}</p>
                        <p className="text-sm text-gray-500 mt-1">{transfer.transfer_type || '流转'}</p>
                      </div>
                      <span className="status-badge status-pending">待确认</span>
                    </div>
                  </div>
                ))
              ) : (
                <p className="text-center text-gray-500 py-4">暂无待确认流转</p>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// frontend/src/routes/dashboard/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { api, type DashboardStats, type TodoItem } from '../../lib/api/client';
  import StatusBadge from '../../lib/components/StatusBadge.svelte';

  let stats: DashboardStats | null = null;
  let todos: TodoItem[] = [];
  let loading = true;
  let error: string | null = null;

  const statCards = [
    { key: 'pendingCount', label: '待处理', icon: '⏳', color: 'from-yellow-400 to-orange-500', bgColor: 'bg-yellow-50' },
    { key: 'rejectedCount', label: '已驳回', icon: '❌', color: 'from-red-400 to-red-600', bgColor: 'bg-red-50' },
    { key: 'reviewNeededCount', label: '需回查', icon: '🔍', color: 'from-blue-400 to-indigo-500', bgColor: 'bg-blue-50' },
    { key: 'totalCampers', label: '营员总数', icon: '👥', color: 'from-green-400 to-emerald-500', bgColor: 'bg-green-50' },
    { key: 'todayAttendanceRate', label: '出勤率', icon: '📊', color: 'from-purple-400 to-pink-500', bgColor: 'bg-purple-50', isPercent: true },
  ];

  function getStatValue(key: string, isPercent: boolean | undefined): string | number {
    if (!stats) return '';
    const value = stats[key as keyof DashboardStats] as number;
    return isPercent ? `${value.toFixed(1)}%` : value;
  }

  function formatDate(dateString: string): string {
    const date = new Date(dateString);
    return date.toLocaleDateString('zh-CN', {
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
    });
  }

  function getStatusColor(status: string): string {
    const colors: Record<string, string> = {
      pending: 'bg-yellow-100 text-yellow-700 border-yellow-200',
      approved: 'bg-green-100 text-green-700 border-green-200',
      rejected: 'bg-red-100 text-red-700 border-red-200',
      fulfilled: 'bg-green-100 text-green-700 border-green-200',
      completed: 'bg-green-100 text-green-700 border-green-200',
    };
    return colors[status] || colors.pending;
  }

  function getStatusLabel(status: string): string {
    const labels: Record<string, string> = {
      pending: '待处理',
      approved: '已通过',
      rejected: '已驳回',
      fulfilled: '已完成',
      completed: '已完成',
    };
    return labels[status] || status;
  }

  function getTypeIcon(type: string): string {
    const icons: Record<string, string> = {
      attendance: '✅',
      medical: '🏥',
      supply: '📦',
      feedback: '💬',
      room: '🏠',
      camper: '👤',
    };
    return icons[type] || '📌';
  }

  onMount(async () => {
    try {
      const [statsData, todosData] = await Promise.all([
        api.getDashboardStats(),
        api.getTodoList(),
      ]);
      stats = statsData;
      todos = todosData;
    } catch (err) {
      error = err instanceof Error ? err.message : '加载数据失败';
    } finally {
      loading = false;
    }
  });
</script>

<div class="space-y-8">
  <div class="flex items-center justify-between">
    <div>
      <h1 class="text-2xl font-bold text-gray-900">首页看板</h1>
      <p class="mt-1 text-sm text-gray-500">欢迎回来，这是您今天的工作概览</p>
    </div>
  </div>

  {#if loading}
    <div class="flex items-center justify-center py-16">
      <div class="text-center">
        <div class="w-12 h-12 border-4 border-blue-200 border-t-blue-600 rounded-full animate-spin mx-auto mb-4" />
        <p class="text-gray-500">加载中...</p>
      </div>
    </div>
  {:else if error}
    <div class="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg">
      {error}
    </div>
  {:else}
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-6">
      {#each statCards as card}
        <div class="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden hover:shadow-md transition-shadow">
          <div class="h-2 bg-gradient-to-r {card.color}" />
          <div class="p-6">
            <div class="flex items-center justify-between mb-4">
              <div class="w-12 h-12 {card.bgColor} rounded-xl flex items-center justify-center text-2xl">
                {card.icon}
              </div>
            </div>
            <p class="text-3xl font-bold text-gray-900">
              {#if stats}
                {getStatValue(card.key, card.isPercent)}
              {/if}
            </p>
            <p class="mt-1 text-sm text-gray-500">{card.label}</p>
          </div>
        </div>
      {/each}
    </div>

    <div class="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
      <div class="px-6 py-4 border-b border-gray-100">
        <h2 class="text-lg font-semibold text-gray-900 flex items-center gap-2">
          <span>📋</span>
          待办事项
          <span class="ml-2 px-2 py-0.5 text-xs font-medium bg-blue-100 text-blue-700 rounded-full">
            {todos.length}
          </span>
        </h2>
      </div>
      <div class="divide-y divide-gray-100">
        {#if todos.length === 0}
          <div class="py-12 text-center text-gray-400">
            <p class="text-4xl mb-2">🎉</p>
            <p class="text-sm">暂无待办事项</p>
          </div>
        {:else}
          {#each todos as todo}
            <div class="px-6 py-4 hover:bg-gray-50 transition-colors">
              <div class="flex items-start gap-4">
                <div class="w-10 h-10 bg-gray-100 rounded-lg flex items-center justify-center text-lg flex-shrink-0">
                  {getTypeIcon(todo.type)}
                </div>
                <div class="flex-1 min-w-0">
                  <div class="flex items-center gap-3">
                    <h3 class="font-medium text-gray-900 truncate">{todo.title}</h3>
                    <span class="px-2 py-0.5 text-xs font-medium rounded-full border {getStatusColor(todo.status)}">
                      {getStatusLabel(todo.status)}
                    </span>
                  </div>
                  <p class="mt-1 text-sm text-gray-500 line-clamp-2">{todo.description}</p>
                  <p class="mt-2 text-xs text-gray-400">{formatDate(todo.created_at)}</p>
                </div>
              </div>
            </div>
          {/each}
        {/if}
      </div>
    </div>
  {/if}
</div>
