// client/app/manager/dashboard/page.tsx
'use client';

import AppLayout from '@/components/layout/AppLayout';
import { api } from '@/services/api';
import { DashboardOverview, Exception, Reconciliation, TrendData } from '@/types';
import { formatCurrency, getExceptionStatusColor, getExceptionStatusLabel, getReconciliationStatusColor, getReconciliationStatusLabel } from '@/utils/format';
import {
    AlertTriangle,
    ArrowDownRight,
    ArrowUpRight,
    Calendar,
    FileText,
    Target,
    TrendingUp,
    Wallet,
} from 'lucide-react';
import { useEffect, useState } from 'react';

export default function DashboardPage() {
  const [overview, setOverview] = useState<DashboardOverview | null>(null);
  const [trends, setTrends] = useState<TrendData[]>([]);
  const [recentReconciliations, setRecentReconciliations] = useState<Reconciliation[]>([]);
  const [pendingExceptions, setPendingExceptions] = useState<Exception[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadData();
  }, []);

  const loadData = async () => {
    try {
      const [overviewRes, trendsRes, reconRes, excepRes] = await Promise.all([
        api.get<DashboardOverview>('/dashboard/overview'),
        api.get<TrendData[]>('/dashboard/trends?days=7'),
        api.get<{ items: Reconciliation[] }>('/reconciliation?pageSize=5'),
        api.get<{ items: Exception[] }>('/exceptions?status=pending&pageSize=5'),
      ]);

      if (overviewRes.success) setOverview(overviewRes.data || null);
      if (trendsRes.success) setTrends(trendsRes.data || []);
      if (reconRes.success) setRecentReconciliations(reconRes.data?.items || []);
      if (excepRes.success) setPendingExceptions(excepRes.data?.items || []);
    } catch (e) {
      console.error('Load error:', e);
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <AppLayout>
        <div className="flex items-center justify-center h-96">
          <div className="text-center">
            <div className="w-12 h-12 border-4 border-primary-600 border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
            <p className="text-gray-500">加载中...</p>
          </div>
        </div>
      </AppLayout>
    );
  }

  const statCards = overview
    ? [
        {
          label: '今日营收',
          value: formatCurrency(overview.today_revenue),
          icon: <TrendingUp size={24} />,
          color: 'bg-green-500',
          bgColor: 'bg-green-50',
          textColor: 'text-green-600',
          trend: '+12.5%',
          trendUp: true,
        },
        {
          label: '储值总余额',
          value: formatCurrency(overview.total_wallet_balance),
          icon: <Wallet size={24} />,
          color: 'bg-blue-500',
          bgColor: 'bg-blue-50',
          textColor: 'text-blue-600',
          trend: '+5.2%',
          trendUp: true,
        },
        {
          label: '今日到场',
          value: `${overview.today_bookings} 人次`,
          icon: <Calendar size={24} />,
          color: 'bg-purple-500',
          bgColor: 'bg-purple-50',
          textColor: 'text-purple-600',
          trend: '+3',
          trendUp: true,
        },
        {
          label: '球道利用率',
          value: `${overview.bay_utilization}%`,
          icon: <Target size={24} />,
          color: 'bg-gold-800',
          bgColor: 'bg-yellow-50',
          textColor: 'text-yellow-600',
          trend: '-2%',
          trendUp: false,
        },
      ]
    : [];

  return (
    <AppLayout>
      <div className="space-y-6">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          {statCards.map((card, index) => (
            <div key={index} className="card">
              <div className="flex items-start justify-between mb-4">
                <div className={`w-12 h-12 ${card.bgColor} rounded-xl flex items-center justify-center ${card.textColor}`}>
                  {card.icon}
                </div>
                <span
                  className={`flex items-center gap-1 text-sm font-medium ${
                    card.trendUp ? 'text-green-600' : 'text-red-600'
                  }`}
                >
                  {card.trendUp ? <ArrowUpRight size={16} /> : <ArrowDownRight size={16} />}
                  {card.trend}
                </span>
              </div>
              <p className="text-sm text-gray-500">{card.label}</p>
              <p className="text-2xl font-bold text-gray-800 mt-1">{card.value}</p>
            </div>
          ))}
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="bg-gradient-to-br from-primary-900 to-primary-700 rounded-xl p-6 text-white">
            <div className="flex items-center justify-between mb-6">
              <h3 className="font-semibold text-lg">近7天收支趋势</h3>
              <div className="flex items-center gap-4 text-sm">
                <span className="flex items-center gap-2">
                  <span className="w-3 h-3 rounded-full bg-green-400"></span> 充值
                </span>
                <span className="flex items-center gap-2">
                  <span className="w-3 h-3 rounded-full bg-red-400"></span> 消费
                </span>
              </div>
            </div>
            <div className="flex items-end justify-between h-48 gap-2">
              {trends.map((day, index) => {
                const maxValue = Math.max(...trends.map((t) => Math.max(t.recharge, t.consume)), 1000);
                const rechargeHeight = (day.recharge / maxValue) * 100;
                const consumeHeight = (day.consume / maxValue) * 100;

                return (
                  <div key={index} className="flex-1 flex flex-col items-center gap-2">
                    <div className="w-full flex items-end justify-center gap-1 h-40">
                      <div
                        className="w-3 bg-green-400 rounded-t transition-all duration-500"
                        style={{ height: `${rechargeHeight}%` }}
                      ></div>
                      <div
                        className="w-3 bg-red-400 rounded-t transition-all duration-500"
                        style={{ height: `${consumeHeight}%` }}
                      ></div>
                    </div>
                    <span className="text-xs text-primary-200">{day.date.slice(5)}</span>
                  </div>
                );
              })}
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="card bg-gradient-to-br from-yellow-50 to-orange-50 border-yellow-200">
              <div className="flex items-center gap-3 mb-3">
                <div className="w-10 h-10 bg-yellow-100 rounded-lg flex items-center justify-center text-yellow-600">
                  <AlertTriangle size={20} />
                </div>
                <div>
                  <p className="text-2xl font-bold text-yellow-700">{overview?.pending_exceptions || 0}</p>
                  <p className="text-sm text-yellow-600">待处理异常</p>
                </div>
              </div>
              <button className="w-full btn-gold text-sm py-2">立即处理</button>
            </div>

            <div className="card bg-gradient-to-br from-blue-50 to-indigo-50 border-blue-200">
              <div className="flex items-center gap-3 mb-3">
                <div className="w-10 h-10 bg-blue-100 rounded-lg flex items-center justify-center text-blue-600">
                  <FileText size={20} />
                </div>
                <div>
                  <p className="text-2xl font-bold text-blue-700">{overview?.pending_reconciliation || 0}</p>
                  <p className="text-sm text-blue-600">待审核对账</p>
                </div>
              </div>
              <button className="w-full bg-blue-600 hover:bg-blue-700 text-white text-sm py-2 rounded-lg transition-colors">
                去审核
              </button>
            </div>

            <div className="col-span-2 card">
              <h4 className="font-semibold text-gray-800 mb-3">储值余额分布</h4>
              <div className="space-y-3">
                <div>
                  <div className="flex justify-between text-sm mb-1">
                    <span className="text-gray-600">本金余额</span>
                    <span className="font-medium">{formatCurrency(overview?.total_principal_balance || 0)}</span>
                  </div>
                  <div className="h-2 bg-gray-200 rounded-full overflow-hidden">
                    <div className="h-full bg-primary-600 rounded-full" style={{ width: `${overview && overview.total_wallet_balance > 0 ? Math.round((overview.total_principal_balance / overview.total_wallet_balance) * 100) : 0}%` }}></div>
                  </div>
                </div>
                <div>
                  <div className="flex justify-between text-sm mb-1">
                    <span className="text-gray-600">赠送金余额</span>
                    <span className="font-medium">{formatCurrency(overview?.total_gift_balance || 0)}</span>
                  </div>
                  <div className="h-2 bg-gray-200 rounded-full overflow-hidden">
                    <div className="h-full bg-gold-800 rounded-full" style={{ width: `${overview && overview.total_wallet_balance > 0 ? Math.round((overview.total_gift_balance / overview.total_wallet_balance) * 100) : 0}%` }}></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <div className="card">
            <div className="flex items-center justify-between mb-4">
              <h3 className="font-semibold text-gray-800">最近对账记录</h3>
              <button className="text-sm text-primary-600 hover:text-primary-700">查看全部</button>
            </div>
            <div className="space-y-3">
              {recentReconciliations.map((recon) => (
                <div key={recon.id} className="flex items-center justify-between p-3 bg-gray-50 rounded-lg">
                  <div>
                    <p className="font-medium">{recon.reconciliation_date}</p>
                    <p className="text-sm text-gray-500">
                      充值: {formatCurrency(recon.total_recharge)} · 消费: {formatCurrency(recon.total_consume)}
                    </p>
                  </div>
                  <span className={`badge ${getReconciliationStatusColor(recon.status)}`}>
                    {getReconciliationStatusLabel(recon.status)}
                  </span>
                </div>
              ))}
            </div>
          </div>

          <div className="card">
            <div className="flex items-center justify-between mb-4">
              <h3 className="font-semibold text-gray-800">待处理异常</h3>
              <button className="text-sm text-primary-600 hover:text-primary-700">查看全部</button>
            </div>
            <div className="space-y-3">
              {pendingExceptions.length > 0 ? (
                pendingExceptions.map((ex) => (
                  <div key={ex.id} className="p-3 bg-red-50 border border-red-200 rounded-lg">
                    <div className="flex items-center justify-between mb-1">
                      <span className="font-medium text-red-800">{ex.title}</span>
                      <span className={`badge ${getExceptionStatusColor(ex.status)}`}>
                        {getExceptionStatusLabel(ex.status)}
                      </span>
                    </div>
                    <p className="text-sm text-red-600 line-clamp-2">{ex.description}</p>
                  </div>
                ))
              ) : (
                <p className="text-center text-gray-500 py-8">暂无待处理异常</p>
              )}
            </div>
          </div>
        </div>
      </div>
    </AppLayout>
  );
}

// frontend/src/routes/dashboard/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { api, type DashboardStats, type TodoItem } from '../../lib/api/client';
  import StatusBadge from '../../lib/components/StatusBadge.svelte';

  let stats: DashboardStats | null = null;
  let todos: TodoItem[] = [];
  let loading = true;
  let error: string | null = null;

  const statCards = [
    { key: 'pendingCount', label: '待处理', icon: '⏳', color: 'from-yellow-400 to-orange-500', bgColor: 'bg-yellow-50' },
    { key: 'rejectedCount', label: '已驳回', icon: '❌', color: 'from-red-400 to-red-600', bgColor: 'bg-red-50' },
    { key: 'reviewNeededCount', label: '需回查', icon: '🔍', color: 'from-blue-400 to-indigo-500', bgColor: 'bg-blue-50' },
    { key: 'totalCampers', label: '营员总数', icon: '👥', color: 'from-green-400 to-emerald-500', bgColor: 'bg-green-50' },
    { key: 'todayAttendanceRate', label: '出勤率', icon: '📊', color: 'from-purple-400 to-pink-500', bgColor: 'bg-purple-50', isPercent: true },
  ];

  function getStatValue(key: string, isPercent: boolean | undefined): string | number {
    if (!stats) return '';
    const value = stats[key as keyof DashboardStats] as number;
    return isPercent ? `${value.toFixed(1)}%` : value;
  }

  function formatDate(dateString: string): string {
    const date = new Date(dateString);
    return date.toLocaleDateString('zh-CN', {
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
    });
  }

  function getStatusColor(status: string): string {
    const colors: Record<string, string> = {
      pending: 'bg-yellow-100 text-yellow-700 border-yellow-200',
      approved: 'bg-green-100 text-green-700 border-green-200',
      rejected: 'bg-red-100 text-red-700 border-red-200',
      fulfilled: 'bg-green-100 text-green-700 border-green-200',
      completed: 'bg-green-100 text-green-700 border-green-200',
    };
    return colors[status] || colors.pending;
  }

  function getStatusLabel(status: string): string {
    const labels: Record<string, string> = {
      pending: '待处理',
      approved: '已通过',
      rejected: '已驳回',
      fulfilled: '已完成',
      completed: '已完成',
    };
    return labels[status] || status;
  }

  function getTypeIcon(type: string): string {
    const icons: Record<string, string> = {
      attendance: '✅',
      medical: '🏥',
      supply: '📦',
      feedback: '💬',
      room: '🏠',
      camper: '👤',
    };
    return icons[type] || '📌';
  }

  onMount(async () => {
    try {
      const [statsData, todosData] = await Promise.all([
        api.getDashboardStats(),
        api.getTodoList(),
      ]);
      stats = statsData;
      todos = todosData;
    } catch (err) {
      error = err instanceof Error ? err.message : '加载数据失败';
    } finally {
      loading = false;
    }
  });
</script>

<div class="space-y-8">
  <div class="flex items-center justify-between">
    <div>
      <h1 class="text-2xl font-bold text-gray-900">首页看板</h1>
      <p class="mt-1 text-sm text-gray-500">欢迎回来，这是您今天的工作概览</p>
    </div>
  </div>

  {#if loading}
    <div class="flex items-center justify-center py-16">
      <div class="text-center">
        <div class="w-12 h-12 border-4 border-blue-200 border-t-blue-600 rounded-full animate-spin mx-auto mb-4" />
        <p class="text-gray-500">加载中...</p>
      </div>
    </div>
  {:else if error}
    <div class="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg">
      {error}
    </div>
  {:else}
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-6">
      {#each statCards as card}
        <div class="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden hover:shadow-md transition-shadow">
          <div class="h-2 bg-gradient-to-r {card.color}" />
          <div class="p-6">
            <div class="flex items-center justify-between mb-4">
              <div class="w-12 h-12 {card.bgColor} rounded-xl flex items-center justify-center text-2xl">
                {card.icon}
              </div>
            </div>
            <p class="text-3xl font-bold text-gray-900">
              {#if stats}
                {getStatValue(card.key, card.isPercent)}
              {/if}
            </p>
            <p class="mt-1 text-sm text-gray-500">{card.label}</p>
          </div>
        </div>
      {/each}
    </div>

    <div class="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
      <div class="px-6 py-4 border-b border-gray-100">
        <h2 class="text-lg font-semibold text-gray-900 flex items-center gap-2">
          <span>📋</span>
          待办事项
          <span class="ml-2 px-2 py-0.5 text-xs font-medium bg-blue-100 text-blue-700 rounded-full">
            {todos.length}
          </span>
        </h2>
      </div>
      <div class="divide-y divide-gray-100">
        {#if todos.length === 0}
          <div class="py-12 text-center text-gray-400">
            <p class="text-4xl mb-2">🎉</p>
            <p class="text-sm">暂无待办事项</p>
          </div>
        {:else}
          {#each todos as todo}
            <div class="px-6 py-4 hover:bg-gray-50 transition-colors">
              <div class="flex items-start gap-4">
                <div class="w-10 h-10 bg-gray-100 rounded-lg flex items-center justify-center text-lg flex-shrink-0">
                  {getTypeIcon(todo.type)}
                </div>
                <div class="flex-1 min-w-0">
                  <div class="flex items-center gap-3">
                    <h3 class="font-medium text-gray-900 truncate">{todo.title}</h3>
                    <span class="px-2 py-0.5 text-xs font-medium rounded-full border {getStatusColor(todo.status)}">
                      {getStatusLabel(todo.status)}
                    </span>
                  </div>
                  <p class="mt-1 text-sm text-gray-500 line-clamp-2">{todo.description}</p>
                  <p class="mt-2 text-xs text-gray-400">{formatDate(todo.created_at)}</p>
                </div>
              </div>
            </div>
          {/each}
        {/if}
      </div>
    </div>
  {/if}
</div>
