// frontend/pages/login.vue
<template>
  <div class="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 flex items-center justify-center p-4">
    <div class="w-full max-w-md">
      <div class="card p-8">
        <div class="text-center mb-8">
          <div class="w-16 h-16 bg-blue-600 rounded-xl flex items-center justify-center text-white text-2xl font-bold mx-auto mb-4">
            地
          </div>
          <h1 class="text-2xl font-bold text-gray-900">地坪施工管理系统</h1>
          <p class="text-gray-500 mt-2">工地进度与质量复查平台</p>
        </div>

        <form @submit.prevent="handleLogin" class="space-y-4">
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">用户名</label>
            <input v-model="form.username" type="text" class="input-field" placeholder="请输入用户名" />
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">密码</label>
            <input v-model="form.password" type="password" class="input-field" placeholder="请输入密码" />
          </div>

          <div v-if="error" class="text-red-600 text-sm bg-red-50 p-3 rounded-lg">
            {{ error }}
          </div>

          <button type="submit" class="btn-primary w-full" :disabled="loading">
            {{ loading ? '登录中...' : '登录' }}
          </button>
        </form>

        <div class="mt-6 p-4 bg-gray-50 rounded-lg">
          <p class="text-xs text-gray-500 mb-2">测试账号：</p>
          <div class="text-xs text-gray-600 space-y-1">
            <p>项目负责人：manager / 123456</p>
            <p>质检工程师：inspector / 123456</p>
            <p>班组长：leader1 / 123456</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
const authStore = useAuthStore()
const router = useRouter()

const form = ref({
  username: 'manager',
  password: '123456'
})
const loading = ref(false)
const error = ref('')

const handleLogin = async () => {
  loading.value = true
  error.value = ''
  try {
    await authStore.login(form.value.username, form.value.password)
    router.push('/')
  } catch (e: any) {
    error.value = e.data?.detail || '登录失败，请检查用户名和密码'
  } finally {
    loading.value = false
  }
}
</script>

// web/src/routes/login/+page.svelte
<script>
  import { goto } from '$app/navigation';
  import { user } from '../stores/user';
  import { authAPI } from '$lib/api';
  import { AlertCircle, Lock, User } from 'lucide-svelte';

  let username = 'admin';
  let password = '123456';
  let loading = false;
  let error = '';

  async function handleLogin() {
    loading = true;
    error = '';
    try {
      const res = await authAPI.login({ username, password });
      localStorage.setItem('token', res.token);
      user.login(res.user);
      goto('/');
    } catch (e) {
      error = e.message;
    } finally {
      loading = false;
    }
  }

  $: canSubmit = username && password && !loading;
</script>

<div class="min-h-screen flex items-center justify-center bg-gradient-to-br from-primary-500 to-primary-700">
  <div class="bg-white rounded-2xl shadow-2xl p-8 w-full max-w-md mx-4">
    <div class="text-center mb-8">
      <div class="w-16 h-16 bg-primary-100 rounded-full flex items-center justify-center mx-auto mb-4">
        <svg class="w-8 h-8 text-primary-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
      </div>
      <h1 class="text-2xl font-bold text-gray-900">自助洗车运营平台</h1>
      <p class="text-gray-500 mt-2">会员续费与活动推送系统</p>
    </div>

    <form on:submit|preventDefault={handleLogin} class="space-y-5">
      <div>
        <label class="block text-sm font-medium text-gray-700 mb-2">用户名</label>
        <div class="relative">
          <User class="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
          <input
            type="text"
            bind:value={username}
            class="input pl-10"
            placeholder="请输入用户名"
          />
        </div>
      </div>

      <div>
        <label class="block text-sm font-medium text-gray-700 mb-2">密码</label>
        <div class="relative">
          <Lock class="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
          <input
            type="password"
            bind:value={password}
            class="input pl-10"
            placeholder="请输入密码"
          />
        </div>
      </div>

      {#if error}
        <div class="flex items-center gap-2 p-3 bg-red-50 text-red-700 rounded-lg">
          <AlertCircle class="w-5 h-5" />
          <span class="text-sm">{error}</span>
        </div>
      {/if}

      <button
        type="submit"
        class="btn-primary w-full py-3"
        disabled={!canSubmit}
      >
        {loading ? '登录中...' : '登录'}
      </button>
    </form>

    <div class="mt-6 p-4 bg-gray-50 rounded-lg">
      <p class="text-xs text-gray-500 mb-2">演示账号：</p>
      <div class="text-xs text-gray-600 space-y-1">
        <p>运营主管：admin / 123456</p>
        <p>巡检员：inspector / 123456</p>
        <p>客服：service / 123456</p>
      </div>
    </div>
  </div>
</div>
