// jewelry-system/frontend/src/components/layout/Header.jsx
import { useState } from 'react';
import { useAuth } from '../../context/AuthContext';
import { Users, ChevronDown } from 'lucide-react';

export function Header({ title }) {
  const [showRoleSelector, setShowRoleSelector] = useState(false);
  const { currentRole, ROLES, ROLE_NAMES, switchRole } = useAuth();

  const roleOptions = [
    { value: ROLES.CONSULTANT, label: ROLE_NAMES[ROLES.CONSULTANT] },
    { value: ROLES.COPYWRITER, label: ROLE_NAMES[ROLES.COPYWRITER] },
    { value: ROLES.VISA_ASSISTANT, label: ROLE_NAMES[ROLES.VISA_ASSISTANT] }
  ];

  return (
    <header className="h-16 bg-white border-b border-gray-200 flex items-center justify-between px-6">
      <h1 className="text-xl font-semibold text-gray-900">{title}</h1>
      
      <div className="flex items-center gap-4">
        <div className="relative">
          <button
            onClick={() => setShowRoleSelector(!showRoleSelector)}
            className="flex items-center gap-2 px-3 py-2 bg-gray-50 hover:bg-gray-100 rounded-lg transition-colors"
          >
            <Users className="w-4 h-4 text-gray-500" />
            <span className="text-sm font-medium text-gray-700">
              角色: {ROLE_NAMES[currentRole]}
            </span>
            <ChevronDown className={`w-4 h-4 text-gray-500 transition-transform ${showRoleSelector ? 'rotate-180' : ''}`} />
          </button>

          {showRoleSelector && (
            <div className="absolute right-0 top-full mt-2 w-48 bg-white rounded-lg shadow-lg border border-gray-200 overflow-hidden z-50">
              <div className="p-2">
                {roleOptions.map((option) => (
                  <button
                    key={option.value}
                    onClick={() => {
                      switchRole(option.value);
                      setShowRoleSelector(false);
                    }}
                    className={`w-full text-left px-3 py-2 rounded-md text-sm transition-colors ${
                      currentRole === option.value
                        ? 'bg-primary-50 text-primary-700 font-medium'
                        : 'text-gray-700 hover:bg-gray-50'
                    }`}
                  >
                    {option.label}
                  </button>
                ))}
              </div>
              <div className="px-3 py-2 bg-gray-50 border-t border-gray-100">
                <p className="text-xs text-gray-500">
                  切换角色可体验不同权限的功能视图
                </p>
              </div>
            </div>
          )}
        </div>
      </div>
    </header>
  );
}

// web/src/lib/components/Header.svelte
<script>
  import { page } from '$app/stores';
  import { Bell, Search } from 'lucide-svelte';
  import { user } from '../../stores/user';

  let currentUser = null;
  user.subscribe((v) => (currentUser = v));

  const pageTitles = {
    '/': '首页看板',
    '/members': '会员管理',
    '/memberships': '套餐管理',
    '/orders': '续费订单',
    '/repairs': '设备报修',
    '/refunds': '退款申诉',
    '/activities': '活动推送',
    '/sites': '站点设备',
  };

  $: title = pageTitles[$page.url.pathname] || '首页';
</script>

<header class="bg-white border-b border-gray-200 px-6 py-4">
  <div class="flex items-center justify-between">
    <div>
      <h1 class="text-xl font-bold text-gray-900">{title}</h1>
      <p class="text-sm text-gray-500">
        {new Date().toLocaleDateString('zh-CN', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
      </p>
    </div>

    <div class="flex items-center gap-4">
      <div class="relative">
        <Search class="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
        <input type="text" placeholder="搜索..." class="input pl-9 py-2 w-64 text-sm" />
      </div>

      <button class="relative p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-lg">
        <Bell class="w-5 h-5" />
        <span class="absolute top-1 right-1 w-2 h-2 bg-red-500 rounded-full"></span>
      </button>

      <div class="flex items-center gap-2 pl-4 border-l border-gray-200">
        <div class="w-8 h-8 bg-primary-200 rounded-full flex items-center justify-center">
          <span class="text-primary-700 font-medium text-sm">{currentUser?.name?.charAt(0) || 'U'}</span>
        </div>
      </div>
    </div>
  </div>
</header>
