// src/components/Sidebar.tsx
import { NavLink, useNavigate } from 'react-router-dom'
import {
  LayoutDashboard,
  ClipboardList,
  Wrench,
  MapPin,
  Settings,
  LogOut,
  User,
  ChevronDown,
} from 'lucide-react'
import { useState } from 'react'
import { useAuthStore } from '@/store/useAuthStore'
import { roleLabels } from '@/utils/format'
import type { UserRole } from '@/types'

const navItems = [
  { path: '/dashboard', icon: LayoutDashboard, label: '工作台' },
  { path: '/inspection', icon: ClipboardList, label: '巡检任务' },
  { path: '/workorders', icon: Wrench, label: '工单中心' },
  { path: '/sites', icon: MapPin, label: '站点管理' },
]

export function Sidebar() {
  const { user, logout, switchRole } = useAuthStore()
  const navigate = useNavigate()
  const [showRoleMenu, setShowRoleMenu] = useState(false)

  const handleLogout = () => {
    logout()
    navigate('/login')
  }

  const handleSwitchRole = (role: UserRole) => {
    switchRole(role)
    setShowRoleMenu(false)
  }

  if (!user) return null

  return (
    <aside className="fixed left-0 top-0 h-full w-64 bg-slate-900 text-white flex flex-col z-50">
      <div className="h-16 flex items-center px-6 border-b border-slate-700">
        <div className="w-8 h-8 bg-indigo-500 rounded-lg flex items-center justify-center mr-3">
          <Wrench className="w-5 h-5" />
        </div>
        <div>
          <h1 className="font-bold text-lg">洗车运维</h1>
          <p className="text-xs text-slate-400">场站巡检系统</p>
        </div>
      </div>

      <nav className="flex-1 py-4 px-3">
        <ul className="space-y-1">
          {navItems.map((item) => (
            <li key={item.path}>
              <NavLink
                to={item.path}
                className={({ isActive }) =>
                  `flex items-center px-3 py-2.5 rounded-lg text-sm transition-colors ${
                    isActive
                      ? 'bg-indigo-600 text-white'
                      : 'text-slate-300 hover:bg-slate-800 hover:text-white'
                  }`
                }
              >
                <item.icon className="w-5 h-5 mr-3" />
                {item.label}
              </NavLink>
            </li>
          ))}
        </ul>
      </nav>

      <div className="p-3 border-t border-slate-700">
        <div className="relative">
          <button
            onClick={() => setShowRoleMenu(!showRoleMenu)}
            className="w-full flex items-center px-3 py-2 rounded-lg hover:bg-slate-800 transition-colors"
          >
            <img
              src={user.avatar}
              alt={user.name}
              className="w-9 h-9 rounded-full bg-slate-600 mr-3"
            />
            <div className="flex-1 text-left">
              <p className="text-sm font-medium">{user.name}</p>
              <p className="text-xs text-slate-400">{roleLabels[user.role]}</p>
            </div>
            <ChevronDown className="w-4 h-4 text-slate-400" />
          </button>

          {showRoleMenu && (
            <div className="absolute bottom-full left-0 right-0 mb-2 bg-slate-800 rounded-lg shadow-xl border border-slate-700 overflow-hidden">
              <div className="px-3 py-2 text-xs text-slate-400 border-b border-slate-700">
                切换角色（演示用）
              </div>
              {(['admin', 'inspector', 'service'] as UserRole[]).map((role) => (
                <button
                  key={role}
                  onClick={() => handleSwitchRole(role)}
                  className={`w-full px-3 py-2 text-left text-sm hover:bg-slate-700 transition-colors flex items-center ${
                    user.role === role ? 'text-indigo-400' : 'text-slate-300'
                  }`}
                >
                  <User className="w-4 h-4 mr-2" />
                  {roleLabels[role]}
                  {user.role === role && (
                    <span className="ml-auto text-xs">当前</span>
                  )}
                </button>
              ))}
              <div className="border-t border-slate-700">
                <button
                  onClick={handleLogout}
                  className="w-full px-3 py-2 text-left text-sm text-red-400 hover:bg-slate-700 transition-colors flex items-center"
                >
                  <LogOut className="w-4 h-4 mr-2" />
                  退出登录
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </aside>
  )
}

// web/src/lib/components/Sidebar.svelte
<script>
  import { page } from '$app/stores';
  import { user } from '../../stores/user';
  import { goto } from '$app/navigation';
  import {
    LayoutDashboard,
    Users,
    CreditCard,
    Wrench,
    RefundCcw,
    Megaphone,
    MapPin,
    Settings,
    Package,
  } from 'lucide-svelte';

  let currentUser = null;
  user.subscribe((v) => (currentUser = v));

  const menuItems = [
    { path: '/', label: '首页看板', icon: LayoutDashboard, roles: ['admin', 'inspector', 'service'] },
    { path: '/members', label: '会员管理', icon: Users, roles: ['admin', 'service'] },
    { path: '/memberships', label: '套餐管理', icon: Package, roles: ['admin'] },
    { path: '/orders', label: '续费订单', icon: CreditCard, roles: ['admin', 'service'] },
    { path: '/repairs', label: '设备报修', icon: Wrench, roles: ['admin', 'inspector', 'service'] },
    { path: '/refunds', label: '退款申诉', icon: RefundCcw, roles: ['admin', 'service'] },
    { path: '/activities', label: '活动推送', icon: Megaphone, roles: ['admin'] },
    { path: '/sites', label: '站点设备', icon: MapPin, roles: ['admin', 'inspector'] },
  ];

  function isActive(path) {
    return $page.url.pathname === path;
  }

  function handleLogout() {
    user.logout();
    goto('/login');
  }
</script>

<aside class="w-64 bg-white border-r border-gray-200 flex flex-col">
  <div class="p-6 border-b border-gray-200">
    <div class="flex items-center gap-3">
      <div class="w-10 h-10 bg-primary-100 rounded-lg flex items-center justify-center">
        <svg class="w-6 h-6 text-primary-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
      </div>
      <div>
        <h1 class="font-bold text-gray-900">洗车运营</h1>
        <p class="text-xs text-gray-500">会员管理平台</p>
      </div>
    </div>
  </div>

  <nav class="flex-1 p-4 space-y-1 overflow-y-auto">
    {#each menuItems as item}
      {#if item.roles.includes(currentUser?.role)}
        <a
          href={item.path}
          class="flex items-center gap-3 px-4 py-3 rounded-lg transition-colors {isActive(item.path)
            ? 'bg-primary-50 text-primary-700'
            : 'text-gray-600 hover:bg-gray-50'}"
        >
          <svelte:component this={item.icon} class="w-5 h-5" />
          <span class="font-medium">{item.label}</span>
        </a>
      {/if}
    {/each}
  </nav>

  <div class="p-4 border-t border-gray-200">
    <div class="flex items-center gap-3 px-4 py-3 bg-gray-50 rounded-lg">
      <div class="w-10 h-10 bg-primary-200 rounded-full flex items-center justify-center">
        <span class="text-primary-700 font-medium">{currentUser?.name?.charAt(0) || 'U'}</span>
      </div>
      <div class="flex-1 min-w-0">
        <p class="text-sm font-medium text-gray-900 truncate">{currentUser?.name}</p>
        <p class="text-xs text-gray-500">
          {currentUser?.role === 'admin' ? '运营主管' : currentUser?.role === 'inspector' ? '巡检员' : '客服'}
        </p>
      </div>
      <button on:click={handleLogout} class="text-gray-400 hover:text-gray-600">
        <Settings class="w-5 h-5" />
      </button>
    </div>
  </div>
</aside>
