// jewelry-system/frontend/src/components/common/EmptyState.jsx
import { FileX, Search, Inbox, ClipboardList } from 'lucide-react';

const icons = {
  empty: Inbox,
  search: Search,
  noData: FileX,
  noTasks: ClipboardList
};

export function EmptyState({ 
  icon = 'empty', 
  title = '暂无数据', 
  description = '当前没有可用的数据',
  action,
  className = ''
}) {
  const Icon = icons[icon] || Inbox;

  return (
    <div className={`flex flex-col items-center justify-center py-12 px-4 ${className}`}>
      <div className="w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center mb-4">
        <Icon className="w-8 h-8 text-gray-400" />
      </div>
      <h3 className="text-lg font-medium text-gray-900 mb-2">{title}</h3>
      <p className="text-sm text-gray-500 text-center max-w-sm mb-6">{description}</p>
      {action && action}
    </div>
  );
}

// watch-service-system/components/common/EmptyState.vue
<template>
  <div class="flex flex-col items-center justify-center py-16 px-4">
    <div class="w-20 h-20 mb-6 text-gray-300">
      <Icon :icon="icon" class="w-full h-full" />
    </div>
    <h3 class="text-lg font-medium text-gray-900 mb-2">{{ title }}</h3>
    <p class="text-gray-500 text-center mb-6 max-w-sm">{{ description }}</p>
    <button v-if="showAction" @click="$emit('action')" class="btn-primary">
      <Icon :icon="actionIcon" class="w-4 h-4 mr-2" />
      {{ actionText }}
    </button>
  </div>
</template>

<script setup lang="ts">
interface Props {
  icon?: string;
  title?: string;
  description?: string;
  showAction?: boolean;
  actionIcon?: string;
  actionText?: string;
}

withDefaults(defineProps<Props>(), {
  icon: 'mdi:clipboard-text-outline',
  title: '暂无数据',
  description: '这里还没有任何内容，试试添加新数据或调整筛选条件',
  showAction: false,
  actionIcon: 'mdi:plus',
  actionText: '新建工单',
});

defineEmits<{
  action: [];
}>();
</script>
