// golf-equipment-tracker/src/components/ui/ErrorState.tsx
import React from "react";
import { AlertCircle, RefreshCw } from "lucide-react";

interface ErrorStateProps {
  title?: string;
  message: string;
  onRetry?: () => void;
}

export const ErrorState: React.FC<ErrorStateProps> = ({
  title = "出错了",
  message,
  onRetry,
}) => {
  return (
    <div className="flex flex-col items-center justify-center py-12 px-4 text-center">
      <div className="w-16 h-16 rounded-full bg-red-100 flex items-center justify-center mb-4">
        <AlertCircle className="w-8 h-8 text-red-500" />
      </div>
      <h3 className="text-lg font-medium text-gray-900 mb-2">{title}</h3>
      <p className="text-sm text-gray-500 max-w-sm mb-4">{message}</p>
      {onRetry && (
        <button
          onClick={onRetry}
          className="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
        >
          <RefreshCw className="w-4 h-4 mr-2" />
          重试
        </button>
      )}
    </div>
  );
};

// watch-service-system/components/common/ErrorState.vue
<template>
  <div class="flex flex-col items-center justify-center py-16 px-4">
    <div class="w-20 h-20 mb-6 text-red-400">
      <Icon icon="mdi:alert-circle-outline" class="w-full h-full" />
    </div>
    <h3 class="text-lg font-medium text-gray-900 mb-2">出错了</h3>
    <p class="text-gray-500 text-center mb-6 max-w-sm">{{ message || '加载数据时出现问题，请重试' }}</p>
    <button @click="$emit('retry')" class="btn-primary">
      <Icon icon="mdi:refresh" class="w-4 h-4 mr-2" />
      重试
    </button>
  </div>
</template>

<script setup lang="ts">
interface Props {
  message?: string;
}

defineProps<Props>();

defineEmits<{
  retry: [];
}>();
</script>
