// jewelry-system/frontend/src/components/common/LoadingState.jsx
import { Loader2 } from 'lucide-react';

export function LoadingState({ text = '加载中...', className = '' }) {
  return (
    <div className={`flex flex-col items-center justify-center py-12 ${className}`}>
      <Loader2 className="w-8 h-8 text-primary-600 animate-spin mb-4" />
      <p className="text-sm text-gray-500">{text}</p>
    </div>
  );
}

export function Skeleton({ className = '' }) {
  return (
    <div className={`animate-pulse bg-gray-200 rounded ${className}`} />
  );
}

export function CardSkeleton() {
  return (
    <div className="card p-6">
      <div className="flex items-start justify-between mb-4">
        <Skeleton className="h-5 w-32" />
        <Skeleton className="h-5 w-16" />
      </div>
      <Skeleton className="h-4 w-full mb-2" />
      <Skeleton className="h-4 w-3/4 mb-4" />
      <div className="flex gap-2">
        <Skeleton className="h-8 w-20" />
        <Skeleton className="h-8 w-20" />
      </div>
    </div>
  );
}

// watch-service-system/components/common/LoadingState.vue
<template>
  <div class="flex items-center justify-center py-16">
    <div class="flex flex-col items-center">
      <div class="w-10 h-10 border-4 border-primary-200 border-t-primary-700 rounded-full animate-spin mb-4"></div>
      <p class="text-gray-500 text-sm">{{ text }}</p>
    </div>
  </div>
</template>

<script setup lang="ts">
interface Props {
  text?: string;
}

withDefaults(defineProps<Props>(), {
  text: '加载中...',
});
</script>
