// jewelry-system/frontend/src/components/common/StatusBadge.jsx
import { twMerge } from 'tailwind-merge';

const statusStyles = {
  pending: 'bg-amber-100 text-amber-700',
  pending_supplement: 'bg-orange-100 text-orange-700',
  processing: 'bg-blue-100 text-blue-700',
  in_progress: 'bg-blue-100 text-blue-700',
  under_review: 'bg-purple-100 text-purple-700',
  approved: 'bg-green-100 text-green-700',
  completed: 'bg-green-100 text-green-700',
  rejected: 'bg-red-100 text-red-700',
  returned: 'bg-orange-100 text-orange-700',
  overdue: 'bg-red-100 text-red-700',
  required: 'bg-amber-100 text-amber-700',
  reviewing: 'bg-purple-100 text-purple-700'
};

const priorityStyles = {
  low: 'bg-gray-100 text-gray-600',
  medium: 'bg-blue-100 text-blue-700',
  high: 'bg-orange-100 text-orange-700',
  urgent: 'bg-red-100 text-red-700'
};

export function StatusBadge({ status, text, variant = 'status' }) {
  const styles = variant === 'priority' ? priorityStyles : statusStyles;
  const style = styles[status] || 'bg-gray-100 text-gray-600';

  return (
    <span className={twMerge(
      'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium',
      style
    )}>
      {text}
    </span>
  );
}

// watch-service-system/components/common/StatusBadge.vue
<template>
  <span
    :class="[
      'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium',
      colorClasses
    ]"
  >
    <span :class="['w-1.5 h-1.5 rounded-full mr-1.5', dotClass]"></span>
    {{ label }}
  </span>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { WorkOrderStatus } from '~/types/workorder';
import { STATUS_LABELS, STATUS_COLORS } from '~/utils/constants';

interface Props {
  status: WorkOrderStatus;
}

const props = defineProps<Props>();

const label = computed(() => STATUS_LABELS[props.status]);
const color = computed(() => STATUS_COLORS[props.status]);

const colorClasses = computed(() => {
  const colors: Record<string, string> = {
    amber: 'bg-amber-100 text-amber-800',
    blue: 'bg-blue-100 text-blue-800',
    orange: 'bg-orange-100 text-orange-800',
    red: 'bg-red-100 text-red-800',
    purple: 'bg-purple-100 text-purple-800',
    cyan: 'bg-cyan-100 text-cyan-800',
    green: 'bg-green-100 text-green-800',
    gray: 'bg-gray-100 text-gray-800',
  };
  return colors[color.value] || colors.gray;
});

const dotClass = computed(() => {
  const colors: Record<string, string> = {
    amber: 'bg-amber-500',
    blue: 'bg-blue-500',
    orange: 'bg-orange-500',
    red: 'bg-red-500',
    purple: 'bg-purple-500',
    cyan: 'bg-cyan-500',
    green: 'bg-green-500',
    gray: 'bg-gray-500',
  };
  return colors[color.value] || colors.gray;
});
</script>
